### ISSUE TITLE
Request NonProfit account for Hotjar

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#1]
Hotjar is a tool that allows us to monitor user behavior in a GDPR compliant way. They offer discounts for NonProfit organizations.

The free low-traffic package may already be good enough for now, but we'll quickly outgrow the 2000 pageviews per day if all goes well. Also, the business packages have more advanced features.

We're interested in finding out about the potential discounts for Longfonds, and I think it helps when the contact request comes from a @longfonds.nl email

https://www.hotjar.com/contact

**Comment by maxvisser** [comment]
@dimitriirtimid I could sign-up for hotjar if this helps getting more rich data from the users test.
