### ISSUE TITLE
Mock community dashboard for "Phase: Preparation"

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#11]
This story is related to page 1 and 2 of wireframe document https://github.com/local-motion/product/commit/f9ed3728c1162f4079c6d4eb92bd118d13099270

The goal is to have a clickable wireframe that is already making API calls but uses mock network traffic. This way the client is defining the API and should be captured by https://github.com/local-motion/community-gateway/blob/master/openapi.yaml

Definition of Done:
- [ ] Mock the network and use fake data. For validation sake, at least one set of mock data should represent the exact values in the wireframes.
- [ ] Have frequent discussions with @errrrk around API call choices that you make
- [ ] Actions should be clickable. They should trigger a mock API call and a UI change.
- [x] Chat should be visible as a static view, but it shouldn't be actually working
- [ ] ignore the design from Yasha. Stick to the Material UI example from https://demos.creative-tim.com/material-kit-react/#/. @errrk has somewhat of a working prototype that may be useful.
- [ ] `openapi.yaml` of `community-gateway` is updated to represent the expected API calls made by the mock screens
- [ ] NPM compile failures should break build, currently it's continuing like everything is fine

Subtasks:
- [ ] Task 1...
- [ ] Task 2...

**Comment by errrrk** [comment]
@dimitriirtimid Is this still a valid issue? The other Mock task you've rewritten into a different issue. Do you plan to do the same with this one?

**Comment by maxvisser** [comment]
I will close this issue because it is not actively worked on
