### ISSUE TITLE
Content for the Workspace explanation page

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#125]
## Description

Annemarie reviewed texts and changed them for workspace welcome.

### Text changes for workspace welcome
Title:
[Name of playingground]
Subtitle:
Kom in actie om een speeltuin rookvrij te maken! Wij helpen je daarbij. In 3 stappen kun je ervoor zorgen dat jouw speeltuin rookvrij wordt. Maak een actiepagina aan en ga direct met deze 3 stappen aan de slag.

### phase 1
Phase 1 title: Voorbereiden
Phase description: Zorg voor een goede voorbereiding. Hoe meer mensen de speeltuin rookvrij willen hebben, hoe beter. Een belangrijke stap om het onderwerp op de agenda van het bestuur te krijgen.

### Phase 2 
Phase 2 title: Invoeren
Phase description: De speeltuin wordt rookvrij! Ga samen met het bestuur aan de slag om iedereen over de nieuwe rookvrije afspraak te informeren. 

### Phase 3
Phase 3 title: Onderhouden
Phase description: Wat gebeurt er als mensen toch roken in de speeltuin? Bepaal samen hoe bezoekers zich aan de rookvrije afspraak kunnen houden.

## preview of text added to welcome page
![image](https://user-images.githubusercontent.com/10818702/54999057-c39a3a80-4fcf-11e9-99bb-71053e92f7a9.png)

DoD:
- [ ] added text
- [x] pictures
- [x] layout

**Comment by maxvisser** [comment]
As Yvette is not working on Localmotion anymore we have to find another assignee. If needed I will help write content

**Comment by maxvisser** [comment]
Title:
[Name of playingground]
Subtitle:
Kom in actie om een speeltuin rookvrij te maken! Wij helpen je daarbij. In 3 stappen kun je ervoor zorgen dat jouw speeltuin rookvrij wordt. Maak een actiepagina aan en ga direct met deze 3 stappen aan de slag.

### phase 1
Phase 1 title: Voorbereiden
Phase description: Zorg voor een goede voorbereiding. Hoe meer mensen de speeltuin rookvrij willen hebben, hoe beter. Een belangrijke stap om het onderwerp op de agenda van het bestuur te krijgen.

### Phase 2 
Phase 2 title: Invoeren
Phase description: De speeltuin wordt rookvrij! Ga samen met het bestuur aan de slag om iedereen over de nieuwe rookvrije afspraak te informeren. 

### Phase 3
Phase 3 title: Onderhouden
Phase description: Wat gebeurt er als mensen toch roken in de speeltuin? Bepaal samen hoe bezoekers zich aan de rookvrije afspraak kunnen houden.
