### ISSUE TITLE
Tweak login flow

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#140]
Go through login flow, verify:
- Redirects back to app are working correctly
- Validation errors are showing when e.g. invalid password, invalid code, invalid username, invalid email
- Verify correct auto-fill of browser or that we have to `aria`-something the fields to help the browser understand `username` vs. `email`

Issues:
- [x] Onboarding should be running on `/`
- [ ] `enter` button not working
- [ ] after create and confirm account, password manager fills in username automatically, but when clicking 'sign in' it won't work stating: `Username is required`. Once you actively select the same username from the password manager suggestion list, it'll actually work.
- [x] Layout for reset password "Reset with username"-screen is not great. 
- [x] Layout for reset password "code + new password"-screen is not great.
- [ ] Password manager filling in wrong information on reset password "code + new password"-screen.
- [x] Go to Forgot password. The link to "Nog geen account?" is not working.

**Comment by dylandejonge** [comment]
Autofill problems will probably not occur for new users. @errrrk
