### ISSUE TITLE
Feedback/contact button

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#143]
Users of the platform need to be able to get in touch with a platform moderator to report issues (or whatever is on their mind).

DoD:
- [ ] the button should be on each page
- [ ] clicking the button should open the standard email client with subject and receiver address prefilled
- [ ] receiver (moderator) email address is tbd by @Yvette1971

**Comment by dylandejonge** [comment]
We have to see what package / solution is best for this.

I.E.
https://www.intercom.com/
https://www.tawk.to/

**Comment by Yvette1971** [comment]
What do you want me to do with this point. When I have a quick look at both sites, I can't estimate which is best. What do you recommend?
