### ISSUE TITLE
System does not detect session time out

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#144]
When the user's session has timed-out the client receives a 401 and should try a re-authentication.
Sometime the client does not received a 401, but a graphQL error instead:
{
  "errors" : [ {
    "code" : "9-812",
    "niceMessage" : "User must be authenticated"
  } ]
}

DoD:
- [ ] detect session timeout (401 / graphQL error)
- [ ] re-authenticate
- [ ] retry the original request
- [ ] on failure trigger the login flow

See userNotAuthenticatedErrorHandler in QueryActions.js

**Comment by AnandAili** [comment]
I am working on triggering login page for the following scenario,
1. login page for the user not logged in.
And we are refreshing the session which expires.

**Comment by errrrk** [comment]
Much related to #131

**Comment by dimitriirtimid** [comment]
server returns a 401. A reauthenticate has to be triggered (no new login required)

**Comment by dimitriirtimid** [comment]
Solve with 20 minutes session refresh
