### ISSUE TITLE
403 forbidden after login

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#145]
After login the system directs to the map screen, but then freezes into a "loading" state. The console log shows a 403 forbidden response on the graphQL queries

Perhaps this has to do with the graphQL operation name being null?
Request payload as reported by the browser:
{"operationName":null,"variables":{},"query":"{\n  playgrounds {\n    id\n    name\n    lat\n    lng\n    status\n    volunteerCount\n    votes\n    __typename\n  }\n}\n"}

**Comment by errrrk** [comment]
Reverted WAF, everything is working again. Closing.
