### ISSUE TITLE
Show managers of the playground

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#150]
The nicknames of the users who are registered as managers of a playground should be shown in the playgrounds workspace.

(Justification of high-prio: The user needs to be able to confirm that claiming the manager role has been effective processed by the system. In case it takes a considerable amount of effort to implement this feature, this issue can be fixed for now by displaying a message to a user that claims the manager role while already being a manager like "you are already the manager of this playground")

**Comment by errrrk** [comment]
@dylandejonge I'll add a new Graphql endpoint
