### ISSUE TITLE
unsubscribe flow

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#154]
The user should be able to unsubscribe from the system. 

DoD:
- [ ] show unsubscribe / offboard option 
- [ ] delete the user from Cognito's user pool

**Comment by dylandejonge** [comment]
@dimitriirtimid  Do not show a unsubscribe / offboard option in the user profile menu.

This is super confusing for users and it something user shouldn't be bothered with every time they click user profile (or even misclick this option)

**Comment by dimitriirtimid** [comment]
@dylandejonge fine with me.
