### ISSUE TITLE
Possible to signup twice with the same email address

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#168]
Currently it is possible to signup twice with the same email address. This should not be allowed as the email address should be a unique identifier of the user. (I will also causes errors in the application logic.)

DoD:
- [x] display an error message ("e-mail address is already registered, choose reset password if this address belong to you") when somebody tries to sign up with an existing e-mail address

**Comment by AnandAili** [comment]
Error messages will be displayed If email /username is already registered

**Comment by AnandAili** [comment]
please refer branch fix-duplicate-email-address

**Comment by dimitriirtimid** [comment]
Still needs to be integrated, however a server-side solution is preferred and needs to be investigated

**Comment by dimitriirtimid** [comment]
Note that the username is force to be unique from the server side.

**Comment by dimitriirtimid** [comment]
resolved
