### ISSUE TITLE
`Community-bff` should implement `openapi.yaml` but return mock data

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#17]
Story #11 describes how the UI will be predefining the API of this gateway. Once that task is finished, `openapi.yaml` in the `community-bff` repository should have been updated.

Definition of Done:
- [ ] From a UI point of view of the `community-wireframes` or potentially `community-web`, nothing visual has changed. However, under the hood we're no longer mocking the network layer, but it is making actual calls to a the `community-bff`
- [ ] `community-gateway` returns mock data
- [ ] Runs in a docker container on Kube locally
- [ ] Zally linter runs correctly with the exception of oauth2 related complaints (we do not have security in place yet)
- [ ] Tracing propagation is done through Brave
- [x] Either Micronaut or Undertow
- [ ] Centralised error capturing
- [ ] Centralised tracing
- [ ] Centralised logging

Sub-tasks:
- [ ] Research current best practices around API Gateway and Backend-for-frontend stacks - consider using Micronaut since that's likely going to be used for regular services.
- [ ] Kube deployment
- [ ] Route traffic based on context path, e.g. all requests to `api.<server>.<tld>/community/*` to this gateway 
- [ ] Implement fake API endpoints
- [x] Travis build and docker push
- [ ] Fix Zally linter issues
- [ ] API test
- [ ] Journey test (?)

**Comment by maxvisser** [comment]
Max his cleaning service, as this issue is not acitively worked on lets close it for now.
