### ISSUE TITLE
"Get support to support our cause"-functionality

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#18]
See https://github.com/local-motion/product/tree/master/functionality/wireframes 

Note - Screenshot is attached, but please check if there are more recent versions.

Definition of Done:
- [ ] Allow to share on Twitter and Facebook. Ignore Google+
- [ ] Ignore 'Donated Money' icon / functionality
- [ ] Send invite based on comma separated list of emails (I'm assuming Mailchimp has some sort of bulk API as well)
- [ ] All emails should be validated (see how Mailchimp could help us here)
- [ ] Avoid abuse by for example limiting to 50 emails per day (see how Mailchimp could help us here). If someone has problems with that, he/she can take it up with support and we can talk to users of our system to see how they're using it. It's a great contact moment ;). 
- [ ] Invite email template should be created
- [ ] Resend email template should be created
- [ ] Email templates should contain 'unsubscribe' link to avoid spamming this user in the future
- [ ] Expose Mailchimp API integration success/failure/SLO metrics (either using http://micrometer.io/ or preferably through Istio). Discuss with @errrrk when implementing this feature.

![Screen Shot 2018-09-25 at 16.09.37.png](https://images.zenhubusercontent.com/5ba4989cd542104d81ce65ec/d3709423-c1a3-428a-8d6a-ff4ea67a4d15)

**Comment by KarianneHol** [comment]
When testing, what to do with the fact it will be a 'very simple' version of the product? Expectation management? Because it will not be appreciated when online for RVG when not fully in style...
- recruiting participants apart from testing? This can be done in style
- testing only when in RVG style...

**Comment by KarianneHol** [comment]
Ok, we'll go for alfa-test and beta-test. Made an issue about that.

**Comment by maxvisser** [comment]
@jamalv same as #7 I think this is the first use case that we can use such a mail service @pantyukhov

**Comment by dimitriirtimid** [comment]
@maxvisser This item is hopelessly outdated. Please close this issue and (if required) create one or more new ones with the current requirements

**Comment by maxvisser** [comment]
Ok lets close this one and make a new one.

**Comment by maxvisser** [comment]
#252
