### ISSUE TITLE
playground pin symbol

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#187]
The current playground symbol on the pins in the map  are a bit unclear / non-descriptive to me. It takes some time to recognise the slide. Perhaps we should change this to swing symbol that is used by rookvrijegeneratie.nl![Screen Shot 2019-01-08 at 15.58.51.png](https://images.zenhubusercontent.com/5baa62a72b32ff64277503c6/3c8f62d6-dddc-42fc-b5e7-91269b4bfa5d)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/352
![image](https://user-images.githubusercontent.com/6214770/54903406-dbe55900-4eec-11e9-9fd6-a40bdd250ca0.png)
