### ISSUE TITLE
Epic: multi-browser/device support

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#189]
Test the application on these browsers and devices and fix any UI issues:

Windows:
- [x] Edge https://github.com/local-motion/product/issues/384
- [x] Chrome
- [x] Firefox

MacOS:
- [x] Safari https://github.com/local-motion/product/issues/383
- [x] Chrome

iOS
- [x] Safari
- [x] Chrome

Android
- [x] Chrome
- [x] Samsung Internet

**Comment by KarafiziArtur** [comment]
I've checked where I can (iOS chrome, safari, MacOS chrome, safari) - all work for me. Maybe there are some problems related to the backend, but I can't check them.

**Comment by maxvisser** [comment]
application is blank aswell in edge

**Comment by KarafiziArtur** [comment]
I've tried in Edge on Windows - both production and development versions work well. Also I've checked in Chrome and Mozilla on Windows. It works as well.
