### ISSUE TITLE
Mock onboarding flow

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#19]
This story is to get a feel of what the onboarding flow could look like

Pre-requisites
- [x] Initial wireframes are available and approved by @dimitriirtimid and Longfonds (#22)

Definition of Done:
- [ ] "working" mock onboarding flow using clickable react/redux pages. It should be possible to go through the onboarding flow with mock/static data.
- [ ] Mock the networking layer and update `onboarding-gateway`'s `openapi.yaml` to include the API calls that this functionality requires

**Comment by maxvisser** [comment]
Max his cleaning service, as this issue is not acitively worked on lets close it for now.
