### ISSUE TITLE
Back button on information pages

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#197]
All information pages "wie zijn wij", T&C, etc should show a clear back button. Currently the functionality is there(by clicking on "Rookvrije generatie"), but this is not obvious.

DoD
- [x] Move button out of header
- [x] Add back button (history -1)

![image](https://user-images.githubusercontent.com/10818702/55950665-ba5ad000-5c55-11e9-97dd-24eaccb0d360.png)

moving back button out of header leaves room for logo https://github.com/local-motion/product/issues/355

**Comment by AnandAili** [comment]
Should BACK button/link be a part of 
1. dropdown where we have all options signout, User Profile, etc 
2. separate button in the Header beside dropdown.
3. The end of content

**Comment by dimitriirtimid** [comment]
Now points back to map, should be come a history - 1

**Comment by maxvisser** [comment]
In the alpha test the back button did not always have the intended interaction.

**Comment by maxvisser** [comment]
I think we should implement page hierarchy, so we are not depended on a 'back' button'

**Comment by dimitriirtimid** [comment]
I think actually that you want to go 'back' from the information page and to a fixed page (like currently the map page)

**Comment by KarafiziArtur** [comment]
@maxvisser should the back button be implemented on all pages except the main page?

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/410

![image](https://user-images.githubusercontent.com/6214770/56214957-802f6b00-6067-11e9-9094-fd898d6e4e40.png)

![image](https://user-images.githubusercontent.com/6214770/56214982-8cb3c380-6067-11e9-9b60-0417caf039aa.png)
