### ISSUE TITLE
Install Hotjar embeding code

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#2]

**Comment by maxvisser** [comment]
same as #1 ; if usefull, I think should gather some usefull data from the system itself

**Comment by dimitriirtimid** [comment]
We need to decide first on which tool to use for this

**Comment by maxvisser** [comment]
Ok I am not familiar with Hotjar; maybe lets discuss it in #1. I will close this issue.

**Comment by maxvisser** [comment]
As we will use hotjar for beta testing; this issue became relevant again.

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/435

**Comment by maxvisser** [comment]
@jamalv @dimitriirtimid added you two aswell to hotjar account I created.

**Comment by maxvisser** [comment]
I see they offer a feedback button aswell; maybe also usefull.
