### ISSUE TITLE
clarify the add-playground dialog

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#201]
It should be clear to the user to first place the playground pin on the map and then enter the playground's name.

DoD:
- [x] Explicitly tell the user to place the pin on the map
- [x] do not enable the add-playground button until both location and name are specified
- [x] increase the size of the pop-up dialog
- [x] pressing the enter button should submit the form when the add-playground button is enabled

**Comment by maxvisser** [comment]
I think the map in the popup is also really small on desktop. I think we should make the popup fullscreen.

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/353
![image.png](https://images.zenhubusercontent.com/5c90e07cd74bd07972c8903a/a716cf5f-979b-4cef-b1d4-3b7d72d20449)

**Comment by dimitriirtimid** [comment]
@maxvisser I am going to merge in the new-style add-playground dialogue but I do have some comments:
- [ ] full screen looses all context such as headers. Also it starts showing England and Germany. On desktop a little bit smaller would be better I think.
- [ ] I think it is better to first ask for the name and then let the user place the pin. We can then also remove the first sentence "Je staat op het punt om..."
- [ ] We can make the steps more explicit with (1) and (2) icons
- [ ] The maps shows the markers of all current playground. This is good in avoiding the creation of duplicates (people have a change to spot that their playground already exists.) , but when you place the pin in the vicinity of another marker, instead of the pin you get the cluster icon. This is not a proper feedback.
- [ ] Following on the above. Perhaps we should force people to zoom in to a minimum level to avoid people place the markers to roughly.

**Comment by maxvisser** [comment]
I agree leaving some margin top and right will help user to keep some context. I disagree with you to ask name before placing pin as if the playground already exists you entered this unnecessarily. I would like to check first if playground exists by letting the user search for it.

I would make a process of creating a playground: 3 steps;
### Step 1: Search on city name/playground name
show list of already added playground near this city or specifc playground (clickable)
[ Add new playground on map button ] 

### Step 2: Map zoomed in on city (this will help to not show germany)
--- *validation happens here* -----

### Step 3: fill in playground name

**Comment by KarafiziArtur** [comment]
@maxvisser  @dimitriirtimid What do you think about Vertical Stepper https://material-ui.com/demos/steppers/#vertical-stepper ?

![image.png](https://images.zenhubusercontent.com/5c90e07cd74bd07972c8903a/4ff18fcd-2511-4c6d-89ee-63d98ac86bb3)

**Comment by maxvisser** [comment]
Lets put this issue on hold

**Comment by maxvisser** [comment]
https://github.com/local-motion/product/issues/331 is new issue
