### ISSUE TITLE
Show volunteers in workspace

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#202]
The actual volunteers should be shown in the workspace, not just the count of volunteers

DoD:
- [x] show the list of user names of the volunteers when the user open the 'Team'  card
- [x] the number of volunteers should shown on the card itself

**Comment by AnandAili** [comment]
This needs changes at both front-end and back-end. And Back-end server connects to Cognito for fetching the list of usernames of the volunteers.

**Comment by maxvisser** [comment]
Workspace overview page shows wrong team count

**Comment by dimitriirtimid** [comment]
I left that one because the page needs to be redesign, but thinking of it the header probably remains as-is, so I will fix it.
