### ISSUE TITLE
Team - Petitions - Donations header

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#203]
A header should be included in the workspace phases page that shows the team, petitions and donations statistics (as they are currently presented on the dashboard page of the workspace)

DoD:
- [x] the header should show the number of volunteers, the number of signed petitions and the collected amount (mock up the stats while the petition/donation functionality is not implemented yet)
- [x] the actual number of volunteer show be displayed

**Comment by maxvisser** [comment]
I thin this one is done; Lets create a new issue if we want to implement more.
