### ISSUE TITLE
Implement strict input validation

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#212]
The validation in the Initiative aggregate need to become more strict.

DoD:
- [x] check all command handlers and determine the acceptable ranges for all data attributes
- [x] document the validation here: https://github.com/local-motion/product/blob/master/technical/validations.md
- [x] 'clean'  the data where need for instance by trimming strings
- [x] validate all input against their ranges (explicitly check that the range lies within the acceptable ranges as opposed to check for error conditions)
- [x] implement unit tests to verify that the services exhibit the expected behaviour

**Comment by dimitriirtimid** [comment]
@AnandAili Can you please comment on the status of this issue? Is all input sufficiently validated or are there gaps?

**Comment by AnandAili** [comment]
This is already done and there are no gaps. Its already in production.

**Comment by AnandAili** [comment]
I will close this line since the code is already moved to production. For any new validation, new issue will be created.
