### ISSUE TITLE
return list of volunteers from playground projection

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#213]
Currently the projection only return the number of volunteers, it should return the complete list. Additionally the user profile projection should return all playgrounds that the user participates in.

DoD:
- [x] playground projection return the list of volunteers
- [x] implemented in the same fashion as the list of managers (so with object that contain both id and name)
- [x] the total volunteer count should remain part of the projection
- [ ] the Profile projection should include the list of playground ids that the user is participating in

**Comment by AnandAili** [comment]
The first three points of the Dod are implemented.
