### ISSUE TITLE
Manager must be volunteer

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#221]
Currently a manager is usually also a volunteer, but sometimes not.

DoD:
- [ ] determine whether managers should always be volunteers as well (or perhaps they are mutually exclusive)
- [ ] implement in accordance this

**Comment by maxvisser** [comment]
@dimitriirtimid I saw in your release notes something about manager now being part of the volunteer list, is one of these fixed? or is this issue about something different?

**Comment by dimitriirtimid** [comment]
Yes, a manager is now by definition a volunteer. (BTW I think it is about time to start rethinking some terms. For instance I prefer 'member' to 'volunteer'). I will create an issue for this.
