### ISSUE TITLE
Refactor events

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#226]
The Event class need to be as future-proof as possible because they will end up in the database which will restrict future refactoring possibilities.

DoD:
- [x] draft a set for guidelines for event classes
- [x] have the guidelines reviewed
- [x] think of and allocted an appropriate package name
- [x] refactor the existing events

**Comment by maxvisser** [comment]
@dimitriirtimid we talked really short about this issue last sprint planning. Could you explain me abit behind the reasoning of using such an event based system? Also what are the existing events?

**Comment by maxvisser** [comment]
history of events instead of looking at a state.
