### ISSUE TITLE
"Distribute flyers"-functionality

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#23]
In order to build support in the neighbourhood, flyering could be an interesting low-tech way of reaching out. This story is about enabling citizens to start flyering.

![Screen Shot 2018-09-26 at 10.37.11.png](https://images.zenhubusercontent.com/5ba4989cd542104d81ce65ec/da1301eb-fdc8-410a-8a00-522afe7498a6)
![Screen Shot 2018-09-26 at 10.37.17.png](https://images.zenhubusercontent.com/5ba4989cd542104d81ce65ec/fb40f356-8add-49d5-9e6c-dacb81724837)

Definition of Done:
- [ ] Allow one of the team members to order flyers, but only if the team size is at least 3.
- [x] Ordering is done by either a simple admin screen for charity org -or- have microservice send an email -or- use a simple 'mailto:' from HTML (discuss with @errrrk and @dimitriirtimid)
- [x] Citizen should be able to indicate that flyers arrived
- [ ] Once flyers arrived, allow to sign up for volunteering to flyer. Or, ask for help with flyering.
- [x] Once it's done, allow indicating it's done.

Questions:
- [ ] Why should the team size be 3? Should we first see if people use it, and then start limiting? We can always choose to send the requesting person an email if it looks like he/she may be abusing.
- [ ] Choose how the 'order' button is sent to Longfonds.

**Comment by maxvisser** [comment]
steps of being able to say 'flyers' have arived and 'i need help distribute flyers' are still really usefull; Also anyone can now order flyers there are no limits on who can order the flyers.

**Comment by dimitriirtimid** [comment]
I am having some doubts on 'flyers have arrived' and 'i need help...'  checkboxes, when they do not actually trigger something. I think either the user's themselves should chat about this, or a 'chatbot' should be triggered which will chat something like "Max has received the flyers, who will help him to distribute them?"
