### ISSUE TITLE
Explanation/welcome page, three phases

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#233]
There are two ways a user gets into localmotion:
- He goes directly via mail or whatsapp to the workspace.
- He lands on localmotion.io or rookvrijspelen.nl and searches for his playground that he wants to make smokefree

For both cases we need an explanation/welcome page.

**LocalMotion welcome**

When users enter the application they should land on a welcome page. This page should contain an explanation of the process of how to use the platform to achieve the goal of smoke-free children playgrounds. Similar (in approach, not in styling) to: https://www.buurkracht.nl/hoe-werkt-het
Or.. Nudge does it like this:
![image](https://user-images.githubusercontent.com/10818702/53169113-ab07c080-35dc-11e9-9ccb-383b0c20da04.png) (it adds a explanation to their footer, could be an MVP)

A placeholder page including working don't-show-me checkbox is already included in the application in src/views/information/welcome.jsx.

DoD:
- [ ] Static page with the goals and approach of, a dont-show-me-anymore checkbox including implementation, look if content of redesign can be used (maybe be optimized) to add to the overviewpage.
- [X] on path ('/welcome') with an automated redirect from / if applicable

**Workspace welcome**
When users visit a workspace that they are not a member of they should get a welcome / explanation page. This page should offer them the possibility to join the workspace. 
@maxvisser Do we want to offer the petition and donation options here as well even though they are not yet implemented?

A initial version is present in src/views/workspace/sections/workspacewelcome.jsx. Routing and joining is already included.

DoD:
- [x] Workspace/Action page explanation
- [X] Volunteers that are already a member of the workspace automatically skip this page
- [X] possibility to join the workspace

**Comment by maxvisser** [comment]
duplicate of #123

**Comment by maxvisser** [comment]
moved content over from #123

**Comment by dimitriirtimid** [comment]
@maxvisser I rewrote a large part of this item. Could you please review / adapt? Also these are actually two items. (I left them together for now, not to make things too confusing)

**Comment by maxvisser** [comment]
I had contact today with a dedicated text writer. This will help greatly with some of the texts

**Comment by jamalv** [comment]
We will pick this up 👍

**Comment by jamalv** [comment]
Discussion with Max, following tasks came out. @maxvisser, please confirm this is what you'd like:

- [ ] The current landing page can be removed / turned off:
<img width="1789" alt="screenshot 2019-03-04 at 14 09 22" src="https://user-images.githubusercontent.com/30194799/53735447-26902a00-3e87-11e9-9960-23738d5babe6.png">

- [ ] An explanation like [this](https://user-images.githubusercontent.com/10818702/53169113-ab07c080-35dc-11e9-9ccb-383b0c20da04.png) can be added to the footer of this page:
**Note:** This page is currently missing a call to action, opened issue: https://github.com/local-motion/product/issues/273
<img width="1789" alt="screenshot 2019-03-04 at 14 11 25" src="https://user-images.githubusercontent.com/30194799/53735511-6820d500-3e87-11e9-871a-ae9b2cb16471.png">
 
- [ ] Update landing page before entering workspace:

**Current design:**
<img width="1789" alt="screenshot 2019-03-04 at 14 15 40" src="https://user-images.githubusercontent.com/30194799/53735718-001ebe80-3e88-11e9-8b59-f7aa5d955653.png">

**Will be replaced with*:**
<img width="1792" alt="screenshot 2019-03-04 at 13 57 05" src="https://user-images.githubusercontent.com/30194799/53734833-6fdf7a00-3e85-11e9-9fec-bd62fb4140c6.png">
* needs updated texts: https://github.com/local-motion/product/issues/274

- [ ] The icons [1][2][3] above the workspace can be replaced with the icons from the info page
<img width="1789" alt="screenshot 2019-03-04 at 14 17 46" src="https://user-images.githubusercontent.com/30194799/53735825-4aa03b00-3e88-11e9-946d-a06d8c6ad19d.png">

**Comment by dimitriirtimid** [comment]
Personally I feel that just a footer is not enough to properly address the questions of first-time visitors. Also the footer is at the bottom :) so not the first thing that people are going to read. It could be sufficient for an MVP though. Perhaps combined with a bit stronger call-to-action on the map page itself?

With respect to the workspace landing page. Note that we have to provide at least two options here: join as a volunteer or just visit/view the workspace. (A third option could be joining as manager, but that can also be done in the workspace itself.) The logic is already there on the existing page, but the new design needs to incorporate these options.

**Comment by maxvisser** [comment]
I see @jamalv did not add my explanation of why I would remove it for now. As currently we have not thought through the tunnel of what we want from a first time visitor implementing the welcome page does more harm than good.

To implement it well we need:
- [ ] An example of such a welcome page on a different platform that implements it with charm
- [ ] A funnel concept of what we want the user to do. call-to-action?

**Comment by jamalv** [comment]
> With respect to the workspace landing page. Note that we have to provide at least two options here: join as a volunteer or just visit/view the workspace. (A third option could be joining as manager, but that can also be done in the workspace itself.) The logic is already there on the existing page, but the new design needs to incorporate these options.

@dimitriirtimid @maxvisser Are we sure about this? I think asking people to make a decision about joining when they don't really know what it is, might be a confusing choice. Imo we should then make it one of the two. Either "Join the workspace" or "Go to the workspace" and not both.

**Comment by jamalv** [comment]
Would recommend "Join the workspace".

**Comment by maxvisser** [comment]
Could be something like this if we do both:

Text on button:
"Ik wil helpen om deze speeltuin rookvrij te maken!" / "I want to help to make this playground smokefree!"

in gray text below:
"Ik wil alleen de huidige status van de speeltuin inzien" / "I only want to see the current status of the playingground"

**Comment by dimitriirtimid** [comment]
@jamalv A work in progress remark: Let's put things in Done after they have merged into master and not while they are still under review. We have a review pipeline we can use for that.

**Comment by dimitriirtimid** [comment]
@maxvisser The workspace welcome page is currently lacking a footer. I propose to include the footer just as on the action pages. ok?

**Comment by maxvisser** [comment]
Need to know what kind of footer you want to include. I would say yes if it is just the menu + logos

**Comment by dimitriirtimid** [comment]
Yes that I what I meant.


Met vriendelijke groeten,
ABN AMRO Bank N.V.

Dimitri Dekker | Solution Architect

Innovation & Technology | IT Solutions | Connectivity & Technology 
Foppingadreef 22 | 1102 BS Amsterdam | Nederland | Interne PAC: AA 4107
Tel.: +31 (0) 20 6 291576 | Mobiel: +31 (0) 6 12442150

Denk aan het milieu voordat u deze e-mail print.
