### ISSUE TITLE
footer: center footer text and logos

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#234]
The footer text and logos are not center
![image](https://user-images.githubusercontent.com/10818702/54998135-a49aa900-4fcd-11e9-9dcd-07789e28271a.png)

DoD:
- [x] Center text
- [x] Center logo's: Hartstichting and Longfonds can still be side-by-side

**Comment by KarafiziArtur** [comment]
@maxvisser Hi!
Now the page with 260px width looks like that:
![image](https://user-images.githubusercontent.com/6214770/54903869-f3711180-4eed-11e9-8059-03ce627b1956.png)

Where is the skew or is it fixed for the moment?

**Comment by maxvisser** [comment]
Yes its fixed; But it still looks a bit weird... will edit the issue.

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/366

![image](https://user-images.githubusercontent.com/6214770/55105417-845a0f80-50dd-11e9-8114-230fe9c80f26.png)

![image](https://user-images.githubusercontent.com/6214770/55105437-9045d180-50dd-11e9-8e23-3cb305ec65db.png)

![image](https://user-images.githubusercontent.com/6214770/55105454-9b98fd00-50dd-11e9-8014-cb309e24b3f4.png)

![image](https://user-images.githubusercontent.com/6214770/55105470-a81d5580-50dd-11e9-848b-1dab855b3c3b.png)

**Comment by dimitriirtimid** [comment]
I will merge the PR, but on my windows/chrome I still get this:
![image](https://user-images.githubusercontent.com/24209923/55294020-3440bd00-53fd-11e9-8b26-11b9d6762753.png)

When I shrink the screen I do get:
![image](https://user-images.githubusercontent.com/24209923/55294033-589c9980-53fd-11e9-9e17-121687662bbe.png)

I think it should also be with the logos beneath the text

**Comment by dimitriirtimid** [comment]
@maxvisser could you have a look at the question above?

**Comment by maxvisser** [comment]
I agree

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/382
Fixed on large screens
