### ISSUE TITLE
Explanation workspace manager actions / symbol

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#235]
Feedback from stakeholder was that it currently not clear which action can only be taken by a workspace manager. The concept of a manager is not clear and only having the symbol at a manger step is not clear.

**Comment by dimitriirtimid** [comment]
Ideas:
- explain on the workspace welcome / explanation page
- make a button of the item. pressing the button could then pop up an explanation dialog.
- change to icon

**Comment by maxvisser** [comment]
If I would pick a different icon than I would choose an account-key icon; it shows that the user needs some kind of permission. Make the icon green if it has permission and red/grey if not.

I also would suggest to make it more clear who is the manager or if the playground does not have a manager.
