### ISSUE TITLE
More context per action card, each card need some content area with explanation of the step

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#238]
Some options:
- [ ] add a tooltip (information hover) to some action symbols to explain to the user what the step entails.
- [ ] add a more information that the user can click where he gets redirected to a details page with alot information of what the step entails.

**Comment by dimitriirtimid** [comment]
Not sure about tooltips in general. The application should be prepared for mobile usage and tooltips don't work on touch screens.

In general I propose to start with a (very) modest amount of content and then see what the user's needs are.

**Comment by maxvisser** [comment]
This is fixed by reordering workspace.
