### ISSUE TITLE
When a step is done add a succes message / introduce new step

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#239]
The user should feel he accomplished a goal while going through the steps. Stakeholder feedback is to add a succes message when a action is set to success (green checkmark on a card)

**Comment by dimitriirtimid** [comment]
@maxvisser Implement by means of a popup? 
(Nice pictures (thumbs-up?), congrats and 'the next step is...'

**Comment by maxvisser** [comment]
If a popup feels natural, I would like that. Another suggestion is to transform the card to show a success message instead of a popup.

**Comment by dimitriirtimid** [comment]
We could change the picture (photo) on the card from one that represents the work to be done into one that represents the result. Technically no problem, but I will require quite some photo searching I'm afraid.

Other option is to stamp that card with an green OK stamp or √ . That is a bit more obvious than the current checkmark item.

**Comment by maxvisser** [comment]
A succes message in my opinion should not be something permanent; It can be one of the following things:
- When you completed a phase we can implement a popup that says 'Gelukt! Je hebt flyers uitgedeeld, een team verzameld en een beheerder gevonden. Je kunt nu gaan uitvoeren. Plan een datum om je locatie rookvrij te maken.'
- When you complete a step in a card like ordering flyers 'Bedankt! De flyers zullen binnen 3 werkdagen worden verstuurd.' or when planning a date to make playground smokefree 'Gelukt! De datum is gezet op 01-01-2020. Dit is de datum dat de speeltuin rookvrij wordt. Plan een moment met al je teamleden bij de speeltuin en ga het vieren! Laat iedereen weten via de website, reglementen dat dit het moment is dat de speeltuin rookvrij wordt.'

**Comment by jamalv** [comment]
It's very valuable to celebrate the successes to increase motivation. For the MVP of this I would keep it simple and show a generic popup after each step is completed, something like:

<img width="1792" alt="53284692-25108480-3758-11e9-82b1-b57eac279c06" src="https://user-images.githubusercontent.com/30194799/56035182-ba2c0480-5d29-11e9-8578-e99ddf4ed8a7.png">
