### ISSUE TITLE
"Need help"-functionality

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#24]
Use a solution like intercom.io (or similar) to create a chat that is always accessible.

Definition of Done:
- [ ] Anyone using the community dashboard should be able to chat with a support person from Longfonds / engineer.

Questions:
- [ ] Having a chat means we need to have people ready to chat with customers. Are we ready to do that? If not, then using a simple 'Feedback' button may be better.

**Comment by maxvisser** [comment]
I like this issue alot, as we at forus also use a LiveChat feature. We got some great user feedback via chat. I move this from the trashbin to icebox
