### ISSUE TITLE
cleanup css: remove sand, drop shadows and make h2 bold

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#240]
![image](https://user-images.githubusercontent.com/10818702/53171512-3c7a3100-35e3-11e9-801d-70f21777fdb1.png)

- [x] remove sand background
- [x] make h2 bold (weight 600)
- [x] move title of playground to h2 and remove it from top menu

With these small changes the page feels less busy and the cards pop out more.

I would suggest to move the < Kaart out of the header bar and just below it and maybe also add the rookvrijegenerate logo in the top menu on the workspace overview page.

**Comment by jamalv** [comment]
<img width="1679" alt="screenshot 2019-02-21 at 14 19 14" src="https://user-images.githubusercontent.com/30194799/53171690-c0341d80-35e3-11e9-92d3-8c595aa57eb5.png">

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/346

![image](https://user-images.githubusercontent.com/6214770/54784403-d5c55300-4c34-11e9-9e39-261122ccdafe.png)

**Comment by maxvisser** [comment]
It already looks so much better, The issue was also for removing the sand also from home.
