### ISSUE TITLE
remove 'being worked on' cards

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#241]
Make a config file in frontend (flags) that we can easily adjust to enable specific placeholder cards again on the frontend. As we want to start testing on the 7th of march, a tester does not need to see the placeholder cards.

**Comment by dimitriirtimid** [comment]
No need for fancy stuff. We can remove a card by commenting out a single line. However I wonder whether this is a good idea. By leaving the cards in there we can get feedback on the desirability of that action. Also the tester can a better feel of the 'final' product. (For beta test it makes more sense to remove work-in-progress stuff.)

**Comment by maxvisser** [comment]
If this is a goal of the test than I would agree. But I think we should aim to have all features in that we would like feedback on. If we want feedback on ideas, concepts or potential actions; I think we should have different test for that.

**Comment by dimitriirtimid** [comment]
As discussed today let's remove them for alphatest. I will deactivate them, so they can be easily reactivated and completed.
