### ISSUE TITLE
add username to top menu dropdown

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#242]
when logged in lets show the user that he is logged in as his user. Currently we show only this icon:

![image](https://user-images.githubusercontent.com/10818702/53171778-f83b6080-35e3-11e9-9322-122ef35caebf.png)

- [x] add a dropdown arrow like github (see https://github.com/local-motion/product/issues/242#issuecomment-467386610)
- [x] add a signed in as: Username in the dropdown or show username when you hover (like google https://github.com/local-motion/product/issues/242#issuecomment-467386610)

**Comment by dimitriirtimid** [comment]
Do you think the user does not remember his name ;) ?

(I don't care, but let's take mobile interaction into account, we do not have too much screen real estate)

**Comment by maxvisser** [comment]
On mobile you can still hide it. I would recommend to show the username somewhere. In a hover or in the dropdown.

**Comment by maxvisser** [comment]
I think you are right @dimitriirtimid I checked multiple platforms and they all don't show a username. They do show a avatar in most instances. 

Some examples of how google shows your username:
![image](https://user-images.githubusercontent.com/10818702/53406397-25a85580-39ba-11e9-82d9-f4ed9560c8fa.png)

Github shows a arrow besides the avatar, this helps the user recognize that the icon is clickable:
![image](https://user-images.githubusercontent.com/10818702/53406475-525c6d00-39ba-11e9-8ab4-f9cafeed18b7.png)

I will change the issue in accordance

**Comment by dimitriirtimid** [comment]
picked up this one from the regular backlog as it helps in the development ;)
Leaving the fancy styling for later

**Comment by maxvisser** [comment]
I think this row should have a special css class that disables the :hover. look a bit weird. But nice to see it so quickly implemented.
