### ISSUE TITLE
add some css to phase-container/wrapper on workspace

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#244]
![image](https://user-images.githubusercontent.com/10818702/53172218-16ee2700-35e5-11e9-9ef2-5c0cbbf24295.png)

- [x] add a 50px margin-top to element so that it is not so close to the header
- [x] make the bars between the phase containers less thick (from 10px to 5px)
- [x] add a padding to the container of the bars so the bar is not so close against each number circle (25px padding)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/343
