### ISSUE TITLE
Implement oAuth in cognito service

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#245]
I see that cognito support oAuth 2.0; as users already have facebook, twiiter or other social media identities this will help onboarding alot.

https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-user-pool-oauth-2-0-grants/

**Comment by jamalv** [comment]
Related to: https://github.com/local-motion/product/issues/264

**Comment by dimitriirtimid** [comment]
Currently investigating. I lean toward not doing this in Cognito though and just use cognito for authenticating users that do not use social login. The sole user registration then lies in our application itself.

**Comment by dimitriirtimid** [comment]
This one has some side-effect that I will describe in a separate issue. Propose to put this one on hold for now.
