### ISSUE TITLE
some playgrounds have been uploaded twice

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#250]
for instance 'Zwembad Amstelbad'

**Comment by maxvisser** [comment]
Is this a bug or something that can be fixed with a database refresh?

**Comment by maxvisser** [comment]
Can this issue be closed @dimitriirtimid

**Comment by dimitriirtimid** [comment]
@maxvisser The problem is in the excelsheet with the playground data. It contains duplicates. 
Because we have implemented a duplicate check duplicate playgrounds are no longer imported, but they should still be removed from the excel sheet to prevent inconsistent data. Can you discuss this with Karianne?

**Comment by dimitriirtimid** [comment]
@maxvisser Can we close this one and perhaps open an issue: 'update/complete playground list'?

**Comment by maxvisser** [comment]
yes, lets do that.
