### ISSUE TITLE
create invite e-mail template

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#253]
A user can join a workspace as a team member and after this he is able to share the workspace with his or her friends. This invitation needs a template email that is send from the system.

- [ ] first use case is that it can already be implemented inside the mailto: @dimitri @dimitriirtimid  what are the limits of the text on this implementation
- [ ] This is also part of the bigger issue of really inviting users via platform instead of using mailto:

**Comment by dimitri** [comment]
I don't think you intended to mention me really, though that's what you did... ;-)

**Comment by maxvisser** [comment]
Hah! That never happened before right? :wink: I indeed meant to tag @dimitriirtimid
