### ISSUE TITLE
Hide volunteer / donation / likes on homepage

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#257]
- [x] Only show these buttons on workspaces:

![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/1b734506-f0d8-47dc-9711-40b2fba7c2b7)

- [x] hide icons on root / home page
- [x] only show team icon on workspace

**Comment by dimitriirtimid** [comment]
We can do this of course. But the idea behind this was that it could show the grant totals (all volunteers, all petitions and total donated amount).
What do you think?

**Comment by maxvisser** [comment]
I like the idea of the showing grant totals but I don't think this is the right implementation for it; I will add a seperate issue for showing these grand totals.

I think this implementation is wrong because the first time I saw localmotion I thought it was my friends, euro balance on my account and my total score. 

If I would implement it I would do it more like how rookvrij shows these kind of figures:
![image](https://user-images.githubusercontent.com/10818702/53569490-a30fc980-3b64-11e9-8a3a-e854feb00541.png)

Such a diagram feels more like statistics.

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/341
