### ISSUE TITLE
disable business location pins google maps

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#259]
![image](https://user-images.githubusercontent.com/10818702/53410636-a1a79b00-39c4-11e9-9436-ad68624eb906.png)
A user can confuse these pins with system pins (playground pins) when zoomed in.

Reproduces how often:
Alpha test 2 in version 1.0.8-alpha, user found it confusing

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/364

Before:
![image](https://user-images.githubusercontent.com/6214770/55092404-9c249a00-50c3-11e9-9d0a-366a0bc78ab8.png)

After:
![image](https://user-images.githubusercontent.com/6214770/55092564-d42bdd00-50c3-11e9-8233-fbbaca241278.png)
