### ISSUE TITLE
"Involve playground manager"-functionality

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#26]
There is a distinction between playgrounds and play-areas. 

**Playgrounds**
- In the Netherlands, a Playground is always backed and managed by an official 'playground organization' that has a comittee and a board.
- They're typically (much) larger than play-areas
- Around 750 playgrounds in the Netherlands
- They may have employees or volunteers to help manage the playground
- But most importantly, **the decision to go 'smoke-free' is made by the committee**. 

**Play-area**
- Around 65.000 play-areas in the Netherlands
- Not managed by anyone

This story is about inviting committee members of the 750 playgrounds. The idea is:
- Build support in the neighbourhood
- Find out who's on the committee
- Contact the committee and invite them to the community dashboard
- Provide tools and material to the committee member to convince him/her, so that he/she in turn can convince the remainder of the committee. Material could include impactful scientific tidbits of information that can help convince.
- If the invite is not accepted, the community can for example start a drip feed of emails to the playground committee. Each email would be coming from a different citizen, and all would ask when the playground becomes smoke-free.

**Definition of Done:**
- [ ] See Tips on how to find and contact the committee, including for example email examples
- [ ] Allows inviting a committee member (playground manager)
- [ ] Allow marking yourself as playground manager
- [ ] Allow starting a drip feed campaign, this functionality is described in #27 and is not part of this story.

Questions:
- [ ] The 'tips' button mentioned a 'list of playgrounds in the area'. I'm not sure how that helps, since the screen assumes you're already part of a playground initiative. Why would the list be helpful as Tip?
- [ ] Is playground manager the official terminology we intend to use? I think it would be more descripotive to find a term that is more related to organizations / committee
- [ ] When the invite is accepted, should he/she be marked as the playground manager by default?
- [ ] Is it possible to invite multiple people?
- [ ] With regards to the 'Playground agrees to become smoke-free'; Shouldn't only the manager be able to mark this as yes or no? 
- [ ] And, should we allow for 'comments / notes' whenever yes or no is clicked? 
- [ ] We would need to discuss this feature and provide wireframes describing the on-boarding experience of a playground manager @dimitriirtimid 

![Screen Shot 2018-09-26 at 12.25.17.png](https://images.zenhubusercontent.com/5ba4989cd542104d81ce65ec/5f624d26-50c0-44af-8069-a16dac81f4d8)
![Screen Shot 2018-09-26 at 12.25.21.png](https://images.zenhubusercontent.com/5ba4989cd542104d81ce65ec/87b0fccd-d8dd-4255-895e-844d4b6ff650)

**Comment by maxvisser** [comment]
Max his cleaning service, as this issue is not actively worked on lets close it for now.
