### ISSUE TITLE
Make decision on UI: Cards or Task-list 

### ISSUE THREAD

**Issue by jamalv** [local-motion/product#263]
## Context
There are currently two concepts for the arrangement of the workspace. One version uses a more free approach of cards, the other a more guided approach of using steps. Both have not been tested yet.

## Proposal
We need to make a desicion on which version we will use for the application. We have decided that this decicion will be made based on user feedback from the alpha test https://github.com/local-motion/product/issues/41. 
- [ ] get both applications ready to perform a user test
- [ ] track results of user test and present at a sprint demo
- [ ] make the desicion and either keep the cards or replace them with the tasklist

**Comment by maxvisser** [comment]
I will close https://github.com/local-motion/product/issues/229 in favor of this one.

**Comment by maxvisser** [comment]
In alpha test 1 I asked if the user wanted to be helped like in the step-by-step list or if they want to be let free in with cards. They chose a list of steps with context and liked overall design of the task-list.
