### ISSUE TITLE
proposal: cards to a right aligned column

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#266]
![image.png](https://images.zenhubusercontent.com/5ba4ae539f1e9e096ebdcc88/de856862-b1c6-4d84-bbaa-d4f4ef0a3a3a)

If we outline cards to the right this will open up the posibility to write a motivational text / content on the left.

This content area will contain:
- [ ] Step-by-step explanation of all the cards
- [ ] Why is it important for you to make the playground smokefree
- [ ] Examples of other success stories
- [ ] A video of the current phase

I think this can be also a solution for #263; 

As we start working on these issues already with a content writer:
#125
#126 

we should figure out if we don't need extra content soon.

**Comment by jamalv** [comment]
I think this is a good step. I would suggest to wireframe this, including the content area, before implementing.

**Comment by maxvisser** [comment]
Its just an idea I had. If we keep the cards we should definitely still think on how to keep the user motivated without any gamification (as this takes long to implement well), great content, motivational text and other can really help engage with the user.
