### ISSUE TITLE
"Drip feed campaign"-functionality

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#27]
This task is an extension to #26

Whenever a playground is unconvinced or unwilling to become smoke-free, the community can choose to start drip feed of emails. Let's say there are 25 people in the community, then each day a different community member could send an email to the organization asking when they intend to become smoke-free.

**Definition of Done:**
- [ ] ... 

**Questions:**
- [ ] We'll need to brainstorm a bit about this functionality
- [ ] Also, we should consider if this is the 'lowest hanging fruit' with regards to convincing the playground committee. I have a suspicion there are easier ways if we think about it a bit more. @dimitriirtimid

**Comment by maxvisser** [comment]
I move this to open for contributions; I like ideas as this as these would be community efforts of making a playground smokefree.
