### ISSUE TITLE
Prepare “list version” for Alpha test

### ISSUE THREAD

**Issue by jamalv** [local-motion/product#272]
To be ready for the alpha test, we need to make a couple minor changes;

- [x] Add some “interaction” to the first step (outlined below)
  - [x] make some designs with alex
  - [x] add to demo with oxana
- [x] Link the bottom three tabs to the pages (without using black icon in top left)
- [x] Hide icon in top left
- [x] Hide top playground and info bar (for now)

<img width="1792" alt="actiepagina" src="https://user-images.githubusercontent.com/30194799/53686190-5541bf80-3d24-11e9-8fe3-5430dca7a228.png">

**Comment by maxvisser** [comment]
Do you already know how you want to host this?

**Comment by jamalv** [comment]
Not yet, we could run it locally for the test. Otherwise we could host it at forus or abn?

**Comment by jamalv** [comment]
http://demo.rookvrij.s3-website-eu-west-1.amazonaws.com
