### ISSUE TITLE
Playgrounds overview lacks a call to action

### ISSUE THREAD

**Issue by jamalv** [local-motion/product#273]
Currently this page is missing a call to action, probably it will not be clear for the user what they need to do.

<img width="1789" alt="screenshot 2019-03-04 at 14 06 28" src="https://user-images.githubusercontent.com/30194799/53735278-b7b2d100-3e86-11e9-8d69-2914e8ae554e.png">

DoD:
- [ ] implemented way to communicate with the user so they know what is expected of them

**Comment by maxvisser** [comment]
The white text below the blue h1 (in rookvrijegeneratie font) is not readable because of the white sand background.

**Comment by jamalv** [comment]
I think we want people to search? If so we should make the search bar more inviting.

Maybe add a slightly animated arrow (graphic) in front of the text?

> Vul hier de naam..

**Comment by maxvisser** [comment]
As we will redesign the front page I will close this issue for now.
