### ISSUE TITLE
Update info page texts

### ISSUE THREAD

**Issue by jamalv** [local-motion/product#274]
This info page will be placed before the workspace:

<img width="1792" alt="screenshot 2019-03-04 at 13 57 05" src="https://user-images.githubusercontent.com/30194799/53736060-f9dd1200-3e88-11e9-8454-c109ab728ede.png">

They currently are too long and not very inviting to read. It should be short, sweet and informative :) @maxvisser I heard there is a new content writer, could you ask him/her to pick this up?

Document with current texts:

[Infopagina content.docx](https://github.com/local-motion/product/files/2926498/Infopagina.content.docx)

**Comment by jknnr** [comment]
wow! radical XD

**Comment by jamalv** [comment]
Hehe, yea, don't know if the content writer already came up with something for this (@maxvisser?), but in the meantime I think we can use this. Short and sweet 😉

**Comment by maxvisser** [comment]
No Annemarie will call me tomorrow

**Comment by maxvisser** [comment]
Issue deprecated; new issue https://github.com/local-motion/product/issues/337
