### ISSUE TITLE
A volunteer should auto join after login from welcome page.

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#276]
When a user that is not logged in chooses to join an initiative ( 'Sluit je aan') he is directed to login. However after login he should automatically join the initiative and land on the action page.

DoD:
- [x]  after login let the user join the selected initiative and direct to the action pages
- [x] if the user does a signup+login, do the same followup as above
- [x] if the user turns out to be already a member of the workspace, do not try a join, but just direct the user to the action page

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/342
