### ISSUE TITLE
status info on phase indicator

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#277]
The newly style phase indicator lacks an indication of the active phase. This should be added again.

**Comment by maxvisser** [comment]
I would suggest adding check marks to the phases that are done instead and giving a dropshadow to the phase that is active and make it slightly bigger.

**Comment by dimitriirtimid** [comment]
fine by me. I would not make it bigger though. That is currently the indicator of the phase that is selected by the user.

**Comment by maxvisser** [comment]
Deprecated because of reordering
