### ISSUE TITLE
"Decision = smoke-free" functionality

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#28]
This story describes the stage where a playground mgr has found the playground committee willing to commit to a smoke-free date. When they do, Longfonds has a specific logo (HTML code) that should be pasted on the website. It should include a statement of the exact date the playground will become smoke-free.

Additionally, there are smart dates on which to communicate these kind of things; e.g. new year time period, beginning of spring. We're providing a 'Smart smoke-free date'-picker.

**Definition of Done:**
- [ ] Playground manager can download logo + html snippet zip file.
- [ ] Allow playground manager to state that the web site has been updated with logo and smoke-free date commitment text
- [ ] Display tips on how and when to communicate the smoke-free decision

**Questions:**
- [ ] Can community members also download logo and mark 'website is updated'? If so, why? @dimitriirtimid 
- [ ] As an alternative to download logo, we could allow the playground mgr to provide the email address of its IT partner / department / person. The email could include a technical explanation of what needs to be done. @dimitriirtimid 

![Screen Shot 2018-09-26 at 12.52.09.png](https://images.zenhubusercontent.com/5ba4989cd542104d81ce65ec/5012e6ce-dc92-4f29-9175-791744824ac8)
![Screen Shot 2018-09-26 at 12.52.13.png](https://images.zenhubusercontent.com/5ba4989cd542104d81ce65ec/caa2f6d8-6214-4a6d-a0d9-4328c7865d98)

**Comment by maxvisser** [comment]
This is done as an mvp. Issue is old and therefor closed.
