### ISSUE TITLE
Volunteer wants to add playingground when not logged in or get authenticated while doing so.

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#282]
## Description

Volunteer looked up her area on the map of the frontpage where she knows that there is a playingground but could not add it while she was not logged in.

**Expected behavior:**
It should be clear how to add a playingground, user should be able to add one and get user flow on how to get authenticated.

**Actual behavior:**
User gets hold off on adding a playing ground while having the intention of doing so.

**Reproduces how often:**
Alpha test 1 on version 1.0.7-alpha

---

## Proposal

- [x] Add a CTA button 'Speeltuin toevoegen' -> Make it easy for the user to get authenticated from this button.

**Comment by KarafiziArtur** [comment]
@maxvisser Could use please explain the behaviour of this:
should Add Playground Pin always visible and when a user clicks to this pin we should redirect him to the login page and after logging in he sees opened AddPlayground modal and can add new playground?

**Comment by maxvisser** [comment]
Hi Arthur this issue can be resolved by fixing #334
