### ISSUE TITLE
Authentication and authorization

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#29]
Roles:
- Community member or citizen
- Playground mgr or committee member?

Authentication mechanisms:
- Facebook
- Twitter
- Invite link in email (playground mgr)

**Definition of Done:**
- [ ] Citizens can login
- [ ] Playground managers can login
- [ ] ... ?

Question:
- [ ] We have to define ubiquitous names for the roles 
- [ ] Decide on which auth parties we want to use. Facebook? Twitter? Google?
- [ ] Do we require playground mgr to log in through Facebook/Twitter? Or do we make it low-barrier and use the invite link to immediately login? If so, how would he login again in the future (cookies only work when same browser)?
- [ ] Can we make this work through Istio?
- [ ] Zally requires oauth2; Do we really need oauth2, and if not, should we ignore oauth2 rules in Zally and replace with a simpler version?

@dimitriirtimid, these questions require some discussion and input

**Comment by maxvisser** [comment]
Max his cleaning service, as this issue is not acitively worked on lets close it for now.

#245 is a replacement issue.
