### ISSUE TITLE
A volunteer should more easily find a way to chat with team

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#293]
## Description
The volunteer asked in the feedback time if the platform will also help with connecting people.

**Expected behavior:**
User recognized that the workspace offers a chat functionality

**Actual behavior:** 
User did not recognize, we got feedback on the icon used (use a different one) and that in the beginning it should just be mention CHAT as text.

**Reproduces on which version:** 
Alpha test 1 - 1.0.7-alpha and on redesign list demo

---

## Proposal
- Make a menu item for team/chat
- Add bot message that welcomes each team member and add red dot that signales new chat message.

**Comment by jamalv** [comment]
I think we should post a welcome message in the chat and then add a (red) notification badge to the icon. The notification badge can show the number of unread messages.

**Comment by maxvisser** [comment]
Community tab fixed this issue.
