### ISSUE TITLE
playground search does not map on special characters

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#295]
An u-umlaut (ü) character does not match when searching for playgrounds. See if string normalisation can provide an outcome.

DoD
- [x] special characters match on an exact match with the search characters (for instance ü -> ü)
- [x] special characters match on a related 'normal' character (for instance u -> ü)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/368

![image](https://user-images.githubusercontent.com/6214770/55108652-14e81e00-50e5-11e9-8841-270a3f919c5e.png)

![image](https://user-images.githubusercontent.com/6214770/55108660-1c0f2c00-50e5-11e9-8977-17327df1768f.png)
