### ISSUE TITLE
translate input placeholder on login

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#299]
Currently some fields on login page are still in the English language. We should translate these strings.

DoD
- [x] Username should be 'Gebruikersnaam' but because you need to fill in E-mailadres as a username while login we should maybe replace it with 'Emailadres'
- [x] Password should be 'Wachtwoord'
- [x] Email addres should be 'Emailadres'

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/354
