### ISSUE TITLE
double playground name on welcome page.

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#306]
![image](https://user-images.githubusercontent.com/10818702/54340643-1d961a00-4638-11e9-9feb-150cddfe538d.png)

DoD
- [x] remove playground name from header menu
- [x] add css of darker blue to the playground name on the welcome page.

I would suggest to move the playground also out of the header on the pages of the phases. As it is a bit confusing that first the logo of smokefree generation was there. (on the place in header where currently the playground name is implemented)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/365

![image.png](https://images.zenhubusercontent.com/5c90e07cd74bd07972c8903a/ebdefc1a-97f6-4d3b-8b5c-1c3985632cb1)
