### ISSUE TITLE
RFC: make adding playgrounds a step

### ISSUE THREAD

**Issue by jamalv** [local-motion/product#308]
## Context
In alpha test 1, people got stuck adding a playground. I have thought about how to make this proces more user friendly, and think rethinking our approach might be wise. This RFC is to draft that proposal.

## Problem
The current website shows a map of the whole country. It is difficult for people to end up with their location, and they are not yet motivated to take a lot of action to perform these actions. In reality this page can cause a lot of drop-off. The barrier is high, and there is not enough context yet.

## Proposal
Make "find or add your playground" the first step. Making this a step has a few advantages: 
* The user takes the first step into learning the mechanics of the application (completing steps)
* The first step is something that they can do from home, it is a small step and an "early win"
  * The second step (inviting friends) is also an "easy" one
  * The third step is more difficult (talking to the board) but the user will already have some momentum and investment into the process after having completed the first two steps (and optionally having been rewarded for it #246)

This is how it could look when using the steps version: 

<img width="1792" alt="step 1" src="https://user-images.githubusercontent.com/30194799/54370626-39211500-4678-11e9-9e57-61eb73919dc5.png">

_**note:** instead we could ask for "city, street name", we could additionally ask for the device location_

<img width="1792" alt="step 2" src="https://user-images.githubusercontent.com/30194799/54370633-3b836f00-4678-11e9-9654-beba464b2c1c.png">

<img width="1792" alt="speeltuin toevoegen" src="https://user-images.githubusercontent.com/30194799/54733028-7fee9d80-4b97-11e9-948f-a3ed540d3444.png">

<img width="1792" alt="speeltuin toevoegen 2" src="https://user-images.githubusercontent.com/30194799/54733038-8b41c900-4b97-11e9-9518-e958a4f3edfa.png">

**Comment by maxvisser** [comment]
why not let the call to action be 
postcode field, housenumber

![image](https://user-images.githubusercontent.com/10818702/54596441-f4f59200-4a34-11e9-900d-618f6d45a6f8.png)

when you enter the fields and press search you will be redirected to a page with list of playgrounds in your area.
