### ISSUE TITLE
Phase: Preparation - Testing hypothesis (1)

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#31]
The wireframe screens make assumptions; It's important we are consciously making assumptions., so how do we identity the assumptions and how do we validate them? 

**Definition of Done:**
- List of assumptions somewhere in repository `local-motion/product/functionality` 
- Include possible ways to validate them 

**Questions:**
- [ ] Based on the Phase: Preparation wireframes, we should define hypothesis and ways to test them.

**Comment by maxvisser** [comment]
As we are starting alpha testing after next sprint demo I think this issue is outdated.
