### ISSUE TITLE
Reconsider password requirements

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#314]
The password requirements are now very strict (capital letter, minimum length, digit, special character). Perhaps we should simplify this somewhat

**Comment by maxvisser** [comment]
In alpha test 2 and 3 users choose a password without capital and special character both times, First time the system gave an error on capital letter, second time on special character. 

If we keep the password requirement this strict we should definitely add a direct indication of how strong the password is. red if not possible, yellow if possible but not strong, green if strong.

**Comment by dimitriirtimid** [comment]
Refactoring the code at the moment. I have included indicators for the password requirement. Not (yet) for the password strength, although I doubt that is necessary with the current requirements. 
I did test and found that we are able to adjust the password requirements even when the userpool is in use. So no urgency on this issue.

**Comment by dimitriirtimid** [comment]
Indicators are including. closing this issue.
