### ISSUE TITLE
A volunteer wants to be able click a link from email to direct login instead of copy pasting a code.

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#316]
## Description

When you signup as a user on Rookvrijspelen.nl you get an e-mail that contains a activation code. In version 1.0.9-alpha you need to copypaste this code into a input field on the platform to activate your account.

DoD:
- [x] add a link to the e-mail send to the user that links the user to rookvrijspelen.nl/activate_account/[code] (or some other link) to activate the account so the user does not need to copypaste a code.

**Comment by dimitriirtimid** [comment]
This requires the ability for the system to be able to send emails (as opposed to opening the email client on the user's device).

**Comment by maxvisser** [comment]
I will add some context, maybe you misunderstood

**Comment by maxvisser** [comment]
@dimitriirtimid you did some research into this subject, did you got any conclusion if it is doable?
