### ISSUE TITLE
Login asks for username but needs email address

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#317]
When a volunteer wants to login he has to fill in his username and password. The username field is bugged, user needs to fill in his e-mail adres instead of the username (field tells the user something else)
- [ ] reproduce the error (as this does not always occur)
- [ ] come up with solution and discuss with Dimitri
- [ ] Change required data field to username (instead of e-mail) as intended.

**Comment by KarafiziArtur** [comment]
Can't reproduce the bug. Maybe there are any other actions that you do when the bug appears?

**Comment by maxvisser** [comment]
I tried reproducing it myself, it happens when I first login (it does not log me in with username + password); second try it works

**Comment by maxvisser** [comment]
Tested it again seems fixed
