### ISSUE TITLE
A volunteer read through terms of use, while having filled in password and username, form was empty when going back.

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#320]
Volunteer lost all progress of signup, this is really frustrating and user would normally leave the application.

DoD
- [x] open terms of use in new window or popup modal.

Reproduces how often:
Alpha test 3 - 1.0.8-alpha

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/408
