### ISSUE TITLE
very white chat page

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#325]
After implementing issue 346 the chat page has a very white appearance:
![image.png](https://images.zenhubusercontent.com/5baa62a72b32ff64277503c6/0dcdacfb-79ea-4170-9cec-5c6ec5fdd11d)

Add some color perhaps?

**Comment by maxvisser** [comment]
Team Al me lo cna be in font of smoke free generation;
chatbox can be more grey #fcfcfc

**Comment by maxvisser** [comment]
we can also implement more of the redesign elements on the team page
![image](https://user-images.githubusercontent.com/10818702/54986143-6643c080-4fb2-11e9-9514-4ea179e19433.png)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/375

![image](https://user-images.githubusercontent.com/6214770/55259423-a5a23380-5276-11e9-94f5-df12f871548d.png)
