### ISSUE TITLE
When you lose internet connection you get a network error

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#328]
## Description

When an user is on an unstable internet connection (like 2g or 3g) or a hotspot, he can be easily temporarily be disconnected from an internet connection. Currently a user gets a Network error when this happens:
![Screenshot_1](https://user-images.githubusercontent.com/10818702/54995724-b711e400-4fc7-11e9-973e-5802650ae55e.png)

If we keep such dialog we should show it in a non-intrusive notification popup in the right bottom corner. I personally think such dialog is not needed and can be removed.

DoD:
- [x] reproduce issue
- [x] Remove dialog from appearing
- [x] reimplement if necassary on a non-intrusive manner

**Comment by dimitriirtimid** [comment]
Solved like this:
![image](https://user-images.githubusercontent.com/24209923/62282899-b0e9b380-b450-11e9-971a-43decfbfecb2.png)
