### ISSUE TITLE
Change buttons on workspace welcome

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#329]
## Description

Currently we added two buttons on the workspace welcome; this was confusing in alpha test 2 and 3.

Buttons need to change based on the action that the user takes with pressing the button

- [x] When user in not logged in, orange CTA button, needs to contain the text 'Doe mee en meld je aan!'
- [x] When logged in the button should contain the text 'Doe mee, ga naar de actieve stap!'
- [ ] When user is already in team of playingground; Text should be 'Ga naar de actieve stap!'

![image](https://user-images.githubusercontent.com/10818702/54999256-24297780-4fd0-11e9-87f2-db9eb4b838dd.png)

**Comment by maxvisser** [comment]
Issue is deprecated because this page is removed.

**Comment by KarafiziArtur** [comment]
> * [ ]  When user is already in team of playingground; Text should be 'Ga naar de actieve stap!'


Now when the user is already joined to the team he automatically redirected to active step after trying to reach this page. So which behaviour is preferred?

**Comment by KarafiziArtur** [comment]
@maxvisser also there is a question: should the bottom button be displayed? It doesn't exist in new design of Workspace Welcome page.

**Comment by maxvisser** [comment]
No lets not implement the grey button/textlink

**Comment by maxvisser** [comment]
> > * [ ]   When user is already in team of playingground; Text should be 'Ga naar de actieve stap!'
> 
> Now when the user is already joined to the team he automatically redirected to active step after trying to reach this page. So which behaviour is preferred?

this is intended behaviour; its only a textual change when user is already in team. 'Doe mee en' can be removed from the button
