### ISSUE TITLE
The stripe under the footer

### ISSUE THREAD

**Issue by jknnr** [local-motion/product#330]
Find why is it there and remove it, so the footer will look good in terms of size.

<img width="1423" alt="Screenshot 2019-03-26 at 16 59 24" src="https://user-images.githubusercontent.com/32199937/55014501-5b595200-4feb-11e9-9953-10189f6d6c86.png">

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/367
