### ISSUE TITLE
UI redesign: Frontpage / Marketing

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#335]
## Description

In a discussion we came upon the conclusion the frontpage also needs a design.

- [x] jumbotron with image and call to action
- [x] block for reason to start / statistics: (make statistics modular, we dont have all statistics yet:)
  - how many playinggrounds are smokefree
  - percentage of all playingrounds
  - Showing grant total of volunteers
  -  money raised for playgrounds
  - signatures https://github.com/local-motion/product/issues/270
- [x] About us block

![image](https://user-images.githubusercontent.com/10818702/55548680-4a3bcf80-56d4-11e9-858c-ca22738ab80a.png)

- [x] Block: Map

![image](https://user-images.githubusercontent.com/10818702/55550215-ff23bb80-56d7-11e9-95b8-2d5e1ff3523b.png)

- [x] Footer block
![image](https://user-images.githubusercontent.com/10818702/55551279-be797180-56da-11e9-9a1f-9d37f7bebbab.png)

## Wireframe
wireframe is a really raw sketch
![image](https://user-images.githubusercontent.com/10818702/55551464-27f98000-56db-11e9-82c9-2f4fa028ff19.png)

## Move this block also to home

![image](https://user-images.githubusercontent.com/10818702/55788609-e8ef7400-5ab8-11e9-8679-806960311e8c.png)

## Inspiration

https://www.buurtaed.nl
https://www.rookvrijegeneratie.nl

**Comment by sashooa** [comment]
https://www.dropbox.com/s/mdv7ps4w6eo7wh2/Frontpage.png?dl=0
https://www.dropbox.com/s/v5qcs3posoq36rs/Frontpage.tif?dl=0

**Comment by maxvisser** [comment]
Hi @sashooa could you also look at mobile?

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/56487256-e0486600-64da-11e9-8acf-539ed0b51af2.png)

## text:

Hoe maak je een speeltuin rookvrij?

Je wilt je inzetten voor een rookvrije speeltuin, dat is een geweldige eerste stap! Hoe meer mensen jouw speeltuin rookvrij willen hebben, hoe groter de kans dat het bestuur van deze speeltuin hiermee aan de slag gaat. In 3 fases kun je ervoor zorgen dat jouw speeltuin rookvrij wordt. Maak een actiepagina aan en ga direct aan de slag.

Voorbereiden
Zorg voor een goede voorbereiding. Hoe meer mensen de speeltuin rookvrij willen hebben, hoe beter. Een belangrijke stap om het onderwerp op de agenda van het bestuur te krijgen.

Invoeren
De speeltuin wordt rookvrij! Ga samen met het bestuur aan de slag om iedereen over de nieuwe rookvrije afspraak te informeren. 

Onderhouden
Wat gebeurt er als mensen toch roken in de speeltuin? Bepaal samen hoe bezoekers zich aan de rookvrije afspraak kunnen houden.

Start een actie!
