### ISSUE TITLE
Routing translate to dutch / SEO optimalization

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#342]
## Description

We created new routes for each page of the workspace; all routes on the workspace are currently in English. This issue is about specing out all routes and rename them to dutch equivalents.

Reasons to this are SEO optimalization and because links are shared frequently so they should look and feel correct for a dutch user.

## Routing specification
Current | New route
--|--
/workspace | /actie
/workspace/b3b8b218-894e-4c91-b53d-0c5f87130e90/ | /actie/Wildlands-Adventure-Zoo-894e/
/actie/Wildlands-Adventure-Zoo-894e/login | /actie/Wildlands-Adventure-Zoo-894e/inloggen
/actie/Wildlands-Adventure-Zoo-894e/add-playground | /actie/Wildlands-Adventure-Zoo-894e/zoeken
/terms | /gebruiksvoorwaarden
/faq | /veelgestelde-vragen
/privacy | /privacyverklaring
/about | /over-ons
/contact | /contact

All the routes of cards of step-by-step guide should be the title of the cards example:

Current | New route
--|--
/workspace/b3b8b218-894e-4c91-b53d-0c5f87130e90/involve-administrator | /actie/Wildlands-Adventure-Zoo-894e/contact-leggen-met-bestuur

DoD
- [x] spec out all routes
- [x] translate routes
- [ ] adjust all route names

**Comment by maxvisser** [comment]
refined issue

**Comment by KarafiziArtur** [comment]
@maxvisser Hi! Should the text of footer also be changed?

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/453

![image](https://user-images.githubusercontent.com/6214770/58029465-51ecf180-7b25-11e9-989b-a5d6dc94697c.png)
