### ISSUE TITLE
Remove 'Ga terug naar de startpagina' button

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#343]
## Description

On workspace there is a blue button below playground name; as this button will have no use anymore after we move the page linked to this button to the workspace aswell; lets remove it

![image](https://user-images.githubusercontent.com/10818702/55783589-0b7c8f80-5aaf-11e9-85b8-f475d111e895.png)

## Definition of Done

- [x] remove button

**Comment by KarafiziArtur** [comment]
Done! Pushed to reordering-workspace PR. https://github.com/local-motion/onboarding-web/pull/379/commits/8cbc1e0b9e876a569652e0e7d268d513b682dbff
