### ISSUE TITLE
Implement previous / next card functionality

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#344]
## Description

In the redesign there is a element that is used to have the CTA and two arrows to go to next and previous card.

![image](https://user-images.githubusercontent.com/10818702/55784142-374c4500-5ab0-11e9-8877-f5667ac24c90.png)

## Definition of Done

- [x] add previous button
- [x] add next button
- [x] ~~add CTA~~ https://github.com/local-motion/product/issues/357
   - [x] ~~some cards need all checkmarks to be checked to make CTA active.~~ https://github.com/local-motion/product/issues/357

**Comment by dimitriirtimid** [comment]
@maxvisser Can you explain the intended working of the "ik heb deze stap volbracht!" button? For me this button seems to contradict with concept that people go through the steps together as opposed to individually. I am curious on how you see this.

**Comment by maxvisser** [comment]
I am still not really sure on the implementation; But this is how I see it:
Each step has a CTA:
Flyers verspreiden -> CTA: 'BESTEL FLYERS'
Betrek beheerder -> CTA: 'Stuur uitnodiging'
Wij worden rookvrij! -> CTA: 'Ja wij worden rookvrij'

Some steps though have multiple checkboxes that need to be checked; I find these steps from the user point of view abit difficult; a news article, or website adjustment can already be done by a team member and does not need to be worked on again. as in they need to check each checkbox to get a checkmark / succeed in the step. In these kind of steps, with multiple checkboxes, the CTA can be 'Ik heb deze stap volbracht'; as sometimes the user does not need to check each checkbox;

**Comment by maxvisser** [comment]
lets move discussion to different issue https://github.com/local-motion/product/issues/357

**Comment by KarafiziArtur** [comment]
Done previous and next button's functionality
https://github.com/local-motion/onboarding-web/pull/395
