### ISSUE TITLE
Use text from step-by-step guide on cards

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#345]
## Description
In latest sprint demo we decided to use all text from a PDF that is on rookvrijegeneratie.nl/materialen

This will help us speed up filling in the content and also make it possible to go quicker to the phase of beta testing as the text does not need any external approval.

## DoD
- [x] texts are on http://demo.rookvrij.s3-website-eu-west-1.amazonaws.com
- [x] Some card titles need to be changed
- [x] some new cards need to be implemented.

**Comment by maxvisser** [comment]
# Voorbereiden

## Menu-items / h1 titles
Vorm een team -> Mensen verzamelen

### Mensen verzamelen
Steun krijgen van (of binnen) het bestuur is een belangrijke eerste stap. De kans om deze steun te krijgen, is groter wanneer je een aantal mensen om je heen verzamelt die de speelplek ook rookvrij willen maken. 

Probeer om minimaal 2 mensen te verzamelen.

Deel de link om mensen uit te nodigen voor deze actiepagina:
Deel link via email
Deel link door middel van social media

## Betrek de beheerder

Zoek vervolgens contact met het bestuur en leg uit waarom jullie de speelplek rookvrij willen maken. De speeltuin kan alleen rookvrij gemaakt worden samen met een beheerder. Nodig de beheerder uit om samen aan de slag te gaan.

[STUUR UITNODIGING]

Tip: benader het onderwerp altijd positief en spreek over ‘rookvrij’ en niet over een rookverbod. Het bestuur moet achter het plan staan om de speelplek rookvrij te maken, dus zorg ervoor dat het onderwerp op de agenda komt.

Weet je niet wie de beheerder is? Zó kom je erachter.
[TIPS]

Let op: wanneer het om een gemeentelijke, onbeheerde, speeltuin gaat, is het belangrijk om ook contact te leggen met de gemeente. Een gemeente kan een speelplek op vrijwillige basis rookvrij maken, door een rookvrij informatiebord te (laten) plaatsen. Veel speelplekken krijgen subsidie van de gemeente.

[IK BEN DE BEHEERDER VAN DEZE SPEELTUIN]

**Comment by maxvisser** [comment]
# Uitvoeren -> Invoeren

## menu items
Zet in de agenda -> Kies moment van invoering
Deel het besluit -> Communiceer over de rookvrije afspraak
Laat het zien -> Laat zien dat de speeltuin rookvrij is

### Kies een goed moment van invoering
Geweldig, het bestuur heeft besloten dat de speeltuin rookvrij wordt! Nu is het belangrijk om een datum te prikken dat het nieuwe rookvrije beleid ingaat.

Een goed moment is bijvoobeeld:
- de start van een nieuw seizoen, of na de wintersluiting
- een verbouwing of verhuizing
- een ander groot evenement of belangrijke gebeurtenis, zoals de Nationale Buitenspeeldag (www.jantjebeton.nl)

Selecteer de datum waarop de speeltuin rookvrij wordt. (Alleen de beheerder kan deze actie uitvoeren.)

[datepicker]

Tip: organiseer of benut een feestelijk moment waarop de rookvrije afspraak ingaat.

### Communiceer over de rookvrije afspraak

Informeer iedereen op tijd over de rookvrije afspraak en wanneer deze ingaat. Laat mensen weten wat er van hen verwacht wordt. Benoem hierin ook duidelijk het rookvrij houden van de entree. Gebruik alle bestaande communicatiekanalen om de rookvrije afspraak bekend te maken (zoals de website, een nieuwsbrief en sociale media).

[checkbox] Artikel in je nieuwbrief

[checkbox] Plaats het op je website

Laat je horen op social media
[socialmediabuttons]

Informeer ook externe partijen over de rookvrije afspraak, zoals de gemeente, leveranciers en sponsoren.Je kunt ook een persbericht sturen naar de lokale media.

[checkbox] Publiceer een persbericht

Handig: bekijk de voorbeeldteksten en hang de posters op
[Download example text]

Handig: gebruik het voorbeeld persbericht
[Download example text]

### LAAT ZIEN DAT DE SPEELPLEK ROOKVRIJ IS

Een mooi moment! Plaats de rookvrij-borden. Zo is voor iedereen zichtbaar dat de speeltuin rookvrij is. Bestel het bord van de Rookvrije Generatie om bij de ingang van de speeltuin te hangen.

[ BESTEL ]

[checkbox] Het bord is besteld
[checkbox] Hang het bord bij de ingang van de speeltuin

Neem de rookvrije afspraak op in het reglement van de speeltuin. Ga na welke aanpassingen nog nodig zijn voor het rookvrij maken van de speelplek. Haal asbakken weg en ruim alle peuken op. Vervang indien mogelijk speelmaterialen die zijn aangetast door sigaretten, zoals rubberen speeltegels.

Voorbeeld rookvrije afspraak: ‘Onze speel- plek is rookvrij. Dat betekent dat niemand rookt op het speelterrein. We doen dit om- dat we het goede voorbeeld aan kinderen willen geven. Behalve gezond, is rookvrij spelen ook veilig spelen. Uit onderzoek blijkt dat als kinderen anderen zien roken zij later zelf sneller beginnen met roken. Wij vinden een rookvrije en gezonde om- geving voor iedereen belangrijk.’

[checkbox] Pas je reglementen aan
[checkbox] Publiceer nieuwe regels op je website

Mohamed Taheri, Landelijk Platform Rookvrije Speelplaatsen: ‘Bij gesprekken met ouders en de gemeente ben ik van het begin af aan stellig geweest: het ging er niet om of we rookvrij konden spelen, maar wanneer. De kans kwam met de gemeenteraadsverkiezingen.’

**Comment by maxvisser** [comment]
# Onderhouden

## menu-items
We zijn rookvrij 
Volhouden -> Naleven
Evalueren

## We zijn rookvrij
change nothing for now, maybe can be removed? 

## Naleven

Het is belangrijk om afspraken te maken hoe de medewerkers of vrijwilligers omgaan met mensen die toch roken in de speeltuin. Houd er rekening mee dat het naleven van de rookvrije afspraak de eerste weken extra tijd en aandacht vraagt. Het vriendelijk aanspreken van mensen die roken op het terrein (en bij de entree!) is belangrijk. Ga er in eerste instantie vanuit dat iemand niet op de hoogte is van de afspraak. Vraag of hij/zij bekend is met de nieuwe afspraak op de speelplek. Vertel over de rookvrije afspraak en laat degene weten waar hij/zij wel of niet kan roken. Leg ook uit dat de speelplek de afspraak heeft om kinderen het goede voorbeeld te geven.

Geef aan of je iemand hebt zien roken vandaag.
[ROOKVRIJ]   [NIET ROOKVRIJ]

Ga voor tien op een rij, rookvrij!
√√√√√√√√√√

## Evalueren
Evalueer de nieuwe afspraak voor een rookvrije speelplek met het team dat betrokken is bij de invoering. 

Stel hierbij de volgende vragen:
- Houden mensen zich aan de afspraak?
- Zijn zij voldoende geïnformeerd en is de rookvrije afspraak voldoende zichtbaar gemaakt?
- Zijn er aanpassingen nodig om de nieuwe afspraak nog beter zichtbaar te maken?
- Als het terrein nog niet geheel rookvrij is, wat is dan de volgende stap hiernaartoe?
- Vraag eventueel ook ouders en kinderen naar hun mening en suggesties.

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/397
