### ISSUE TITLE
Some banner images are not on the right position-y

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#346]
## Description

Image for 'Vorm een team' and 'Deel het besluit' are not on the right background position y.

## DoD
 - [x] Crop image or position image with css

**Comment by KarafiziArtur** [comment]
Done! Pushed to reordering-workspace PR https://github.com/local-motion/onboarding-web/pull/379/commits/7eeef61e470db5977787719cb9a2c6fdaa7c387b
