### ISSUE TITLE
Menu item css changes

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#347]
## Description

Result should be:
![image](https://user-images.githubusercontent.com/10818702/55790678-27872d80-5abd-11e9-9cbd-d0252bb8b540.png)

## DoD
- [x] all menu-items should have no drop shadow or border;
- [x] all menu-items have text margin 15px instead of 10px;
- [x] inactive menu-items should have background color #f5f5f5
- [x] inactive menu-items have text-color #626262
- [x] active menu-items should have background color #085ca6

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/389

![image](https://user-images.githubusercontent.com/6214770/55827017-e705cf00-5b11-11e9-8285-c8a4a45895fb.png)
