### ISSUE TITLE
signin bug

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#348]
When trying to login as part of the workspace step, the front end throws an error:
![image](https://user-images.githubusercontent.com/24209923/55878409-a901bd00-5b9c-11e9-83c3-c22028d20b92.png)

**Comment by KarafiziArtur** [comment]
Thanks for finding this bug. I've fixed it. Pushed it to reordering-workspace PR https://github.com/local-motion/onboarding-web/pull/379/commits/649d9728e59740ad6692a301dbb26fa8d15461da
