### ISSUE TITLE
Playground project front-end page

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#35]
Mockup front-end for a playground project. No backend connectivity and no persistence should be included in this front-end. The front-end should resemble the wireframes of the preparation and the execution phase. Clicking a phase should display the actions within that phase and it should be clear which phase is selected. Each action should be clickable and resulting in some kind of popup dialog that display the details of that action. Preferably the details already resemble the action details on the wireframes, but they do not need to be complete.

Definition of done:
- [x] Fully clickable dialog of one single playground (hard coded)
- [x] No cookies are set
- [ ] Page should not be indexed by search engines
- [x] No data is persisted in local storage or any other mechanism
- [x] ReactJS with material UI (general or Creative Tim (MIT version)) as front-end framework
- [ ] Production build ready for S3 deployment
- [x] At the bottom (footer) of each screen include this text: "Rookvrije speeltuinen is een initiatief van het Longfonds en ABN AMRO" (NL) or "Smoke-free playgrounds is an initiative of het Longfonds and ABN AMRO" (EN)

**Comment by errrrk** [comment]
How does this task differ from local-motion/product#11

**Comment by KarianneHol** [comment]
_At the bottom (footer) of each screen include this text: "Rookvrije speeltuinen is een initiatief van het Longfonds en ABN AMRO" (NL) or "Smoke-free playground is an initiative of het Longfonds and ABN AMRO" (EN)_  >> This should be discussed. Let me check with Yvette.

**Comment by Yvette1971** [comment]
According to the styleguide of the Rookvrije Generatie there is no footer. 
If we want to mention something about the initiative it has to be clear that smokefree playgrounds are part of the Rookvrije Generatie, an initiatieve from Longfonds, KWF Kankerbestrijding and Hartstichting.
And because that senctence is too long I prefer to mention something about this initiatieve in the menu 'About us' and not in the footer

**Comment by dimitriirtimid** [comment]
I have create a separate issue for this, in order to have this message in an appropriate place in the final application: https://github.com/local-motion/product/issues/99
