### ISSUE TITLE
selected step highlight does not work anymore

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#351]
Since @dimitriirtimid fixed the mounting/unmounting of the workspace component the highlighting of the selected step does not work anymore:
![image](https://user-images.githubusercontent.com/24209923/55880840-d56c0800-5ba1-11e9-923f-83f260ae1a29.png)

This is probably because that is no longer a match on an exact url (on step level).

**Comment by KarafiziArtur** [comment]
Could you please pull last changes of reordering-workspace PR? It seems working for me.

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/391

**Comment by KarafiziArtur** [comment]
I've resolved conflicts
