### ISSUE TITLE
login redirect failing

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#352]
After logging in (both via the header bar and via de step in the workspace) the flow does not resume where the user left off. You are forced to refresh the screen.

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/393

**Comment by KarafiziArtur** [comment]
I've done with this issue. Fixed some errors after merging with `master` and broken travelling between pages.

**Comment by dimitriirtimid** [comment]
it is possible to have to users with the same email address
but only one address can have the status verified
if you log in with one that is not verified , the blank screen occur, while you are still logged in
