### ISSUE TITLE
Move 'Mensen verzamelen' back to phase 'voorbereiden'

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#353]
## Description

I think while adding the team page to the workspace we exidently moved the collecting team members step aswell.

### Definition of done

- [x] Move 'Mensen verzamelen' back to phase 'Voorbereiden'
- [x] Make copy of 'Mensen verzamelen' and call it 'Team' 
- [x] add new team page in community

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/405
