### ISSUE TITLE
Design: Change logo to rookvrij spelen

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#355]
## Description

As we are currently live under the domain https://www.rookvrijspelen.nl we should change logo's in header to rookvrij spelen

## proposal for header
![image](https://user-images.githubusercontent.com/10818702/56953228-50d72e80-6b3c-11e9-8f36-5ebe6dd1f3ea.png)

## Defintion of done

I would like to change it to show part of the sign that a playground gets when they are smokefree.

- [x] change logo to rookvrij spelen: rookvrij should be in bamboo blue
- [x] spelen.nl could just be bamboo font in red color
- [x] Back button also needs to be moved out of header to make room for logo https://github.com/local-motion/product/issues/355

## additional info
![image](https://user-images.githubusercontent.com/10818702/56953551-1de16a80-6b3d-11e9-8aba-b75b7f586c88.png)

## references 
https://rookvrijegeneratie.nl/
https://rookvrijchallenge.nl/

**Comment by maxvisser** [comment]
Updated issue

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/455
