### ISSUE TITLE
remove petition and euro buttons on workspace

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#356]
## Description
As we already decided to remove any functionality that is not implemented yet. this part was still forgotten to be removed.

### Definition of done

- [ ] remove these buttons from workspace:
![image](https://user-images.githubusercontent.com/10818702/55947786-7664cc80-5c4f-11e9-956b-beeaaa3e6a20.png)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/407
