### ISSUE TITLE
Implement new welcome screen to workspace

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#360]
## Description
As designed in https://github.com/local-motion/product/issues/337 lets implement this welcome page.

## Design 
psd available via @jknnr 
![image](https://user-images.githubusercontent.com/10818702/55958998-2d6e4180-5c6a-11e9-9f66-1c0b8b674c53.png)

## Definition of done

Skip smiley, it should not be implemented..

- [x] implement placeholder image
- [x] implement phase indicator
- [x] implement statistics
   - [x] team member count
   - [x] smokefree date: NL: Onbekend EN: unknown date. if filled in: DD/MM/YYYY
- [x] Link team member count to collect team page /add-team-member
- [x] Link smokefree date to  /pick-date
- [x] CTA 'Ga direct aan de slag!'
   - [x] if unauthenticated CTA should link to Login step
   - [x] if authenticated but not part of workspace the button should join the user as a workspace team member and redirects him / her to the active phase

**Comment by jknnr** [comment]
Texts: Actieve fase: Onderhounden
Aantal teamleden 5
Rookvrij datum Onbekend
Ga direct aan de slag

**Comment by maxvisser** [comment]
phase name is ofcourse Onderhouden instead of onderhounden (typo in design)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/403

![image](https://user-images.githubusercontent.com/6214770/56162139-f4b8ca00-5fd3-11e9-97a9-9e1d3268b64a.png)
