### ISSUE TITLE
Add banner and space between text on card 'Meningen verzamelen'

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#361]
![image](https://user-images.githubusercontent.com/10818702/56193492-0aa8a800-6031-11e9-9532-06b91b7a9f60.png)

## Definition of Done
- [x] add banner to meningen verzamelen
   - https://rookvrijegeneratie.nl/wp-content/uploads/2018/08/computer-1185626_1280-1024x682.jpg
- [x] add paragraph end (two new lines) Before 'Deze actiepagina'; indicated by blue selectionbox

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/423

![image](https://user-images.githubusercontent.com/6214770/56730895-ca98a200-6761-11e9-85e2-da81f64cf392.png)

**Comment by maxvisser** [comment]
- [ ] New paragraph should be Before 'Deze actiepagina'
- [ ] Align font-size/spacing/weight

**Comment by KarafiziArtur** [comment]
![image](https://user-images.githubusercontent.com/6214770/57011519-bdb8fa00-6c0a-11e9-8a1c-6a0ca5a464ff.png)
