### ISSUE TITLE
Enhance login card

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#362]
## Description

 - [x] Add banner
   - https://rookvrijegeneratie.nl/wp-content/uploads/2017/08/HR_AdobeRGB_20180822_Rookvrijegeneratie_kinderboerderij_0023-1024x683.jpg
- [x] change h1 to red and make it smaller (like on other cards)
- [x] change h1 text from 'Rookvrije generatie' to 'Inloggen'
- [x] move create account below from 'Wachtwoord vergeten'
- [x] add text above button to create account 
    - **Ben je hier voor de eerste keer?**
Je hoeft je slechts éénmalig te registreren om deel te nemen aan een actie. Na het registeren kun je meteen starten om de speeltuin rookvrij te maken.
- [x] change button css class of create account to CTA
- [x] Add text above login 
   -  Geef een gebruikersnaam en wachtwoord op.
- [x] change 'Inloggen' button css like other CTA on different cards
- [x] change input field css to look more like this:
![image](https://user-images.githubusercontent.com/10818702/56199058-72182500-603c-11e9-92eb-2bc2b2616cdf.png)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/420
![screencapture-login](https://user-images.githubusercontent.com/6214770/56682224-c9b92f00-66d3-11e9-871c-1a5391cd06fd.png)
