### ISSUE TITLE
Show menu on full width on mobile

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#363]
## Description
Current state of workspace: 
![image](https://user-images.githubusercontent.com/10818702/56200018-4b5aee00-603e-11e9-93ca-41cf53b3424a.png)

- [ ] Let show menu on full width:
![image](https://user-images.githubusercontent.com/10818702/56200187-970d9780-603e-11e9-8cd3-c51b4100d50f.png)

- [ ] When clicked show card column on full width:
![image](https://user-images.githubusercontent.com/10818702/56200291-c91ef980-603e-11e9-89a8-cbc383fd8a39.png)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/457
