### ISSUE TITLE
open first step when clicked on phase

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#369]
## Description

When you click on a phase, nothing happens. This issue is about fixing this by opening up the first step of the phase.

## Definition of Done

- [x] When clicked on 'Voorbereiden' -> add-team-member or login should open
- [x] When clicked on 'Invoeren' -> pick-date should be opened
- [x] When clicked on 'Onderhouden' -> celebrate should be opened

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/424
