### ISSUE TITLE
outline netherlands with blue border

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#372]
## Description
example from rookvrij.nl
![image](https://user-images.githubusercontent.com/10818702/56650747-f6475980-6687-11e9-9c6c-c23f2112b136.png)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/450

![image](https://user-images.githubusercontent.com/6214770/57916006-af214280-789a-11e9-8e04-c31d6ecf4b1a.png)
