### ISSUE TITLE
change title from "Local Motion Community" to "Rookvrij Spelen | [page title]"

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#380]
# DoD

- [x] change \<title\> from "Local Motion Community" to "Rookvrij Spelen | [page title]"

key | [page title] 
-- | --
/ | Home
/workspace | Actiepagina
/faq | Veelgestelde vragen
/privacy | Privacyverklaring
/terms | Gebruiksvoorwaarden Platform RookvrijSpelen.nl
/contact | Contact

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/461
