### ISSUE TITLE
Implement statistics

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#382]
We show these statistics on homepage:
![image](https://user-images.githubusercontent.com/10818702/57294897-5fd45880-70c9-11e9-82da-560219cd84e9.png)

- [ ] First number is total of smokefree playgrounds in the Netherlands.

- [ ] Seconds number is amount of volunteers on the platform.

These numbers should be available on the service.

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/462

**Comment by dimitriirtimid** [comment]
@maxvisser can this one be closed?

**Comment by maxvisser** [comment]
yes
