### ISSUE TITLE
wrong authorisation header in Safari

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#383]
When visiting rookvrijspelen.nl in Safari an error message is shown (and persists):
![image](https://user-images.githubusercontent.com/24209923/57386243-42c88400-71b4-11e9-99f8-6793b8dfe304.png)

The reason appears to be that Safari gives preference to the basic authorisation token in the header as opposed to the bearer token. (The basic authorisation token is for the site password and the bearer token for the user credentials.)
So the request for the user profile in Safari sends:
![image](https://user-images.githubusercontent.com/24209923/57386417-933fe180-71b4-11e9-9eb3-a35dc5f33ec4.png)

Whereas the same request in Chrome sends:
![image](https://user-images.githubusercontent.com/24209923/57386449-a94da200-71b4-11e9-982e-71147841593d.png)

Todo:
- [x] Check whether the javascript code can be fixed so Safari sends the bearer token
- [ ] Otherwise move the bearer token to a custom header

**Comment by dimitriirtimid** [comment]
It turns out to be browser-specific behaviour, but it should not be too hard to switch to a different header (I have actually already done this in the past). So I will pick this one up.

**Comment by jamalv** [comment]
I'm also getting this error 🙁
