### ISSUE TITLE
rookvrijspelen.nl does not work in Edge

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#384]
The page remains blank when visiting the site using the Edge browser. For promoting the platform the application should at least work in Edge even if not pixel perfect yet.

**Comment by maxvisser** [comment]
https://github.com/local-motion/product/issues/189 lets check all

**Comment by dimitriirtimid** [comment]
edge bug is fixed, but a cors issue for local testing remains. Will create separate issue
