### ISSUE TITLE
Adjust invite CTA on /add-team-member card

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#387]
## Description

currently we only implemented share via mail on cta. 

## Proposal

 - [x] Lets open a popup that shows people all option for sharing: (example)
![image](https://user-images.githubusercontent.com/10818702/57446699-9a6afc00-7255-11e9-8d66-93f9be017fcb.png)

- [x] text for button 'Deel en laat anderen ook in actie komen'

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/474

![image](https://user-images.githubusercontent.com/6214770/58948388-b00b0d00-8792-11e9-8eb4-e4415396b372.png)

**Comment by dimitriirtimid** [comment]
Closing this issue without implementation.
I think it is more user friendly when the link are available directly on the workspace card. No need for an additional button click.
Regarding the Cta button: Currently we have no way to track that something has actually been shared on social media. We could do this via a checklistitem (visible or invisible), but for now let's leave it like it is.
