### ISSUE TITLE
Enhance ordering flyers card

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#388]
related issues #275 and #318

## Description
Currently we have a few checkboxes on this card and a mailto: to order flyers; As it stands, I find the card pretty chaotic. As we have a PDF that contains  the right flyers lets give the user to download that instead. (instead of ordering it via e-mail)

We can also link on this card to the webshop where you can order posters, flyers and more; https://webshop.rookvrijegeneratie.nl/UserContentStart.aspx?category=35

lets make CTA 'Ik heb flyers uitgedeeld' / I have spread flyers

## DoD
- [x] add [Flyer Rookvrij spelen.online.def.pdf](https://github.com/local-motion/product/files/3161598/Flyer.Rookvrij.spelen.online.def.pdf) for download with preview
- [x] add option for user to go to webshop to order more flyers
- [ ] Show on the page who have spread flyers

**Comment by maxvisser** [comment]
[Flyer Rookvrij spelen.online.def.pdf](https://github.com/local-motion/product/files/3161598/Flyer.Rookvrij.spelen.online.def.pdf)

**Comment by KarafiziArtur** [comment]
I created a popup that shows the preview of pdf and button links below to do related actions along checking the first checkbox (`De flyers zijn besteld`). It needs translations.

![image](https://user-images.githubusercontent.com/6214770/57942479-3a6df880-78da-11e9-9887-48f94646ae80.png)

 I'm not sure about showing a user name who spread flyers, at least it needs change DB schema.

**Comment by maxvisser** [comment]
Let's move send mail and visit webshop out of popup.

Translations: visit webshop 'Bezoek webshop'
Send mail: 'Verstuur e-mail'

**Comment by KarafiziArtur** [comment]
Fixed!
https://github.com/local-motion/onboarding-web/pull/452
