### ISSUE TITLE
outline own chat messages to the right

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#389]
![image](https://user-images.githubusercontent.com/10818702/57450679-757b8680-725f-11e9-92c3-cf39f0210168.png)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/451

![image](https://user-images.githubusercontent.com/6214770/57921614-68d1e080-78a6-11e9-977a-86668a9aa290.png)
