### ISSUE TITLE
Onboarding direct from RVG campaign

### ISSUE THREAD

**Issue by KarianneHol** [local-motion/product#39]
**Definition of done**

- [ ] AVG technical procedure oke by ANR and checked by jurist
- [ ] Use data from RVG campaign
- [ ] No double interfaces
- [ ] Front end suitable with RVG campaign

What else we should look after in this issue? More (technical?) items definition of done?

**Comment by dimitriirtimid** [comment]
@maxvisser Can we close this issue. It's outdated and not really SMART

**Comment by maxvisser** [comment]
I will create a more smart issue when I had the meeting with ANR together with Yvonne.
