### ISSUE TITLE
Mobile responsiveness frontpage

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#393]
# Assignee: @KarafiziArtur 
### Show phase indicator above each phase content
As shown on this screenshot:
![image](https://user-images.githubusercontent.com/10818702/58170338-6fd86480-7c93-11e9-9d07-59b5467a699d.png)
Homepage block for explaining phases is not really responsive. I suggest to make this into a column instead of a row.

### full-width header bar on mobile

header bar is to small for all content
![image](https://user-images.githubusercontent.com/10818702/58170483-d1003800-7c93-11e9-9ab5-96bf50ea4347.png)

### header image too tall, font-size too big, text align left
as you see in the image above; the header image + text could look alot better on mobile.
![image](https://user-images.githubusercontent.com/10818702/58170912-035e6500-7c95-11e9-8d27-6f336af69602.png)

# Definition of done 
- [x] Show phase indicator above each phase content
- [x] full-width header bar on mobile
- [x] header image too tall, font-size too big, text align left

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/459

Resolution 320px:

![screencapture-localhost-3000](https://user-images.githubusercontent.com/6214770/58251051-6a4e4d80-7d6b-11e9-9bf5-ab834a0f0603.png)
