### ISSUE TITLE
Public Beta notification

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#394]
## Description
This issue is about removing username and password from rookvrijspelen.nl

I think its needed to inform users that they are part of a public beta. There are a few things that are needed:

- [x] always a bar on top that shows to user that he is part of a beta
- [x]  add information icon that links to FAQ
- [x] text for bar "U neemt deel aan een publieke test." 

## example

![image](https://user-images.githubusercontent.com/10818702/59662504-5b618c00-91ad-11e9-94cc-238274c67f35.png)

color codes:

#148fe6 (blue)
#fed911 (yellow)

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/58762338-76968f80-854f-11e9-86f3-b9b85c6e0bc2.png)

**Comment by maxvisser** [comment]
maybe with a toggle to collapse to 3px; height

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/496

![image](https://user-images.githubusercontent.com/6214770/60336465-160d3d80-99a9-11e9-844a-7361a85eb967.png)

![image](https://user-images.githubusercontent.com/6214770/60336490-27564a00-99a9-11e9-9d86-2b1d5b51edb6.png)

![image](https://user-images.githubusercontent.com/6214770/60336740-d5fa8a80-99a9-11e9-8729-c525e8d8b13d.png)
