### ISSUE TITLE
See difference between workspace being worked on and newly started ones

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#410]
![image](https://user-images.githubusercontent.com/10818702/59658230-539cea00-91a3-11e9-9790-ac45159f1583.png)

## DoD
- [x] if state of playground is 'initial' or 'voorbereiden' button should indicate this by changing text from 'Sluit je aan' to 'Begin de actie'

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/493
