### ISSUE TITLE
Adjust mobile layout workspace

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#411]
## Overview
<details><summary>Current mobile workspace </summary>

![image](https://user-images.githubusercontent.com/10818702/59658507-200e8f80-91a4-11e9-9e71-4be4df556bd7.png)

</details>

<details><summary>Hamburger menu will open up dropdown</summary>

![image](https://user-images.githubusercontent.com/10818702/59658527-2ef54200-91a4-11e9-9901-80267105fd3a.png)

</details>

## Problems

<details><summary>Sometimes menu is completely hidden</summary>

![image](https://user-images.githubusercontent.com/10818702/59658507-200e8f80-91a4-11e9-9e71-4be4df556bd7.png)

</details>
<details><summary>Back button is implemented to always go back to front page</summary>

![image](https://user-images.githubusercontent.com/10818702/59658580-5cda8680-91a4-11e9-8e65-ae1a9838331a.png)

</details>

## Description
I think menu structure needs to be redone. Phases are to big on this screen. Some things I also suspect: user will use Logo to go back to frontpage and user will use previous and next buttons to switch between steps

## Definition of done

- [x] hide whole menu structure (phases and back button) on mobile
- [x] create mobile only menu (horizontal tabs), pressing a tab will open up first card of phase.
- [x] let previous and next button column (with CTA) be stickied to bottom of screen

## example of horizontal tabs
![image](https://user-images.githubusercontent.com/10818702/59659002-7c25e380-91a5-11e9-853d-80a6fd114adc.png)

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/495

![image](https://user-images.githubusercontent.com/6214770/60278879-d1ca6080-9908-11e9-95bd-1c35f0ce0d0a.png)

![image](https://user-images.githubusercontent.com/6214770/60278902-db53c880-9908-11e9-8c9d-4870869dee41.png)
