### ISSUE TITLE
Clicking on pin 'Wildlands Emmen' results in empty workspace

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#413]
![image](https://user-images.githubusercontent.com/10818702/59663733-f22f4800-91af-11e9-9694-b4ba8aa85f96.png)

Url seems to be broken:
https://rookvrijspelen.nl/actie/dierenpark_emmen/_wildlands

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/497

**Comment by dimitriirtimid** [comment]
Fixed with new url encoding:
https://rookvrijspelen.nl/actie/dierenpark_emmen%2F_wildlands
