### ISSUE TITLE
When a step is done lets add a checkmark

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#414]
## description

issue is adding a checkmark when a card is done:
![image](https://user-images.githubusercontent.com/10818702/59664902-328fc580-91b2-11e9-965b-836f649367ce.png)

![image](https://user-images.githubusercontent.com/10818702/59664916-3885a680-91b2-11e9-8fcb-2ad004b25853.png)

Checkmark css/html can maybe be ripped from demo http://demo.rookvrij.s3-website-eu-west-1.amazonaws.com/actiepagina.html#

**Comment by KarafiziArtur** [comment]
https://github.com/local-motion/onboarding-web/pull/491
