### ISSUE TITLE
Dataset of playgrounds completed

### ISSUE THREAD

**Issue by KarianneHol** [local-motion/product#42]
**Definition of done**

- [ ] Dataset of 395 playgrounds is available (unknown if they are smoke-free)
- [ ] Verwerkersovereenkomst ABN is settled
- [ ] Dataset of new smoke-free playgrounds is available
- [ ] Old dataset of smoke-free playgrounds is updated with new datasets above 
- [ ] Duplications must have been avoided

**Comment by maxvisser** [comment]
Max his cleaning service, as this issue is not acitively worked on lets close it for now.
