### ISSUE TITLE
share on instagram

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#422]
## Description

Feedback from stakeholder of latest sprintdemo to add sharing on instagram.

## tasks
- [ ] add instagram as option on social media share options

**Comment by KarafiziArtur** [comment]
There is no possibility to post an image via API to instagram in a way we want (like twitter or facebook) because of limitations of content publishing https://developers.facebook.com/docs/instagram-api/guides/content-publishing

**Comment by jknnr** [comment]
closing the issue, discussed with Max
