### ISSUE TITLE
User is confused about blue and orange registration button

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#425]
Wat is het verschil tussen het blauwe en oranje blokje om een account aan te maken?

![thumbnail_image001](https://user-images.githubusercontent.com/10818702/60661811-113e0300-9e5b-11e9-88c0-048a347e4a6a.jpg)

"Maak een account" is displayed twice

## tasks
- [ ] remove one of the buttons

**Comment by dimitriirtimid** [comment]
There is no difference, so yes it is confusing. I have already removed the orange button from all other signin/up dialogs. The problem with this one is that the page opens like this:
![image](https://user-images.githubusercontent.com/24209923/62276134-aaa10a80-b443-11e9-8762-11982eb0072a.png)

So without scolling the blue button is invisible.

Proposal: Move the blue 'Maak een account' button upwards so it is place next to the 'Inloggen' button and then the orange button can be removed.
