### ISSUE TITLE
"ik ben de beheerder van deze speeltuin"-button gives no feedback when pressed

### ISSUE THREAD

**Issue by maxvisser** [local-motion/product#426]
![image](https://user-images.githubusercontent.com/10818702/60668121-80bbee80-9e6b-11e9-9bf5-22ca6da342cf.png)

when pressing the button, user would expect a popup saying "you are now playground manager"

NL text: "Je bent nu de beheerder van de speeltuin."

**Comment by dimitriirtimid** [comment]
Also the button does not grey out when the user is already the manager
