### ISSUE TITLE
Local motion logo.

### ISSUE THREAD

**Issue by jamalv** [local-motion/product#45]
**Definition of done:**

- [x] team picked their favourite and gives feedback
- [x] one iteration is done, and feedback is given again
- [x] decision for a version (or to make another iteration) is made
- [x] defined how to use this logo in relation to the smoke-free generation logo

**Comment by jamalv** [comment]
Question that came up during discussion, we should decide:
How important is the localmotion vs smokefree logo, do we need this at all?

**Comment by jamalv** [comment]
From the current versions: https://bit.ly/2yoDXuQ

The vote on slack was unanimous on v4, can we make another iteration on that? Maybe polish it a bit more and try some variations?

feedback from @dimitriirtimid: My vote went to v4, but I do have the feeling that the other icons have more motion in then, however they are still not perfect.

**Comment by jknnr** [comment]
working mainly on the v4, will try to motionize it a bit:)

**Comment by jknnr** [comment]
![logo final 1](https://user-images.githubusercontent.com/32199937/47508546-986ebc00-d874-11e8-86cb-323a9b1bb8d3.png)

**Comment by jamalv** [comment]
I personally like #1 

**Nitpicking:** would like to see the line between the shoulders in the middle smoothened a bit to look more continuous.

<img width="213" alt="screenshot 2018-10-25 at 16 43 59" src="https://user-images.githubusercontent.com/30194799/47508883-38c4e080-d875-11e8-92c7-d5abebbd8a81.png">

**Comment by jknnr** [comment]
![logo final iopt 1](https://user-images.githubusercontent.com/32199937/47553522-a02b7080-d907-11e8-9681-dee9d63df058.png)

**Comment by Yvette1971** [comment]
...sorry a little bit 'mustard after dinner' ;-), but I was triggerd by the question how important the LocalMotion logo is vs smokefree logo initially. In my point of view, in principal we don't use this logo in our extern communication from the Longfonds or the Rookrvije Generatie. Only when we 'sell' the motor Local Motion to third parties.

**Comment by jamalv** [comment]
Yea, I agree. For now I think the only place we will really use it is for example here; on the GitHub project page.

**Comment by jamalv** [comment]
agreed!
