### ISSUE TITLE
User enrollment

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#46]
Implement these specifications:
https://github.com/local-motion/product/blob/master/functionality/users_and_access/identity_and_access_management.md#user-enrollment

Except for:
- the generated password

Implementation details:
- implement using AWS cognito

DoD:
- [x] validate whether cognito can meet these specs and do a change spec request where it cannot
- [ ] integrated in the screen flow (should be an option in the log in dialog)

**Comment by errrrk** [comment]
Added comments  and questions to https://github.com/local-motion/product/commit/7426a73311e0ffbb0185d322ca5884dbfd89d87c#diff-7602a14a977f0cbc2f97fb76b519c279

**Comment by dimitriirtimid** [comment]
agreed with comment
