### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#48]
Implement these specifications:
https://github.com/local-motion/product/blob/master/functionality/users_and_access/identity_and_access_management.md#user-authentication

Except for:
- the generated password

Implementation details:
- implement using AWS cognito

DoD:
- [ ] validate whether cognito can meet these specs and do a change spec request where it cannot
- [ ] integrated in the screen flow (trigger when the user accesses a playground workspace)

**Comment by errrrk** [comment]
Added several questions and comments to https://github.com/local-motion/product/commit/7426a73311e0ffbb0185d322ca5884dbfd89d87c#comments

**Comment by dimitriirtimid** [comment]
replied to some of the comments
