### ISSUE TITLE
User session

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#49]
Implement these specifications:
https://github.com/local-motion/product/blob/master/functionality/users_and_access/identity_and_access_management.md#user-session

Implementation details:
- implement using AWS cognito

DoD:
- [ ] validate whether cognito can meet these specs and do a change spec request where it cannot

**Comment by errrrk** [comment]
Concerns written down at https://github.com/local-motion/product/commit/7426a73311e0ffbb0185d322ca5884dbfd89d87c#r31082318

**Comment by dimitriirtimid** [comment]
Responded to the comment. The main question is whether we want a timeout. Not quite sure of it. What is Cognito's behaviour here?
