### ISSUE TITLE
Get support - share on social media - template

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#54]
Create the templates for the 'Get support'  social media shares

See: https://github.com/local-motion/product/blob/master/functionality/playgroundworkspace/1_preparation_phase_specifications.md#share-on-social-media

**Comment by gerard-payne** [comment]
I've added the frontend code for this with some temporary information.
We'll need a few things.
1. title (Used by Linkedin, Twitter, Facebook Workplace)
2. description (used by Facebook & Linkedin)
3. via (this is the Twitter username for the campaign)
4. hashtags (used by Twitter but Facebook and Facebook Workplace will use the first in the) list

**Comment by dimitriirtimid** [comment]
covered by #255
