### ISSUE TITLE
Involve playground manager

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#59]
Specification: https://github.com/local-motion/product/blob/master/functionality/playgroundworkspace/1_preparation_phase_specifications.md#action-3-involve-playground-manager

Except for:
- displaying the details for known playgrounds

**Comment by dimitriirtimid** [comment]
Done except for displaying contact details of known playgrounds. @maxvisser Do we still intend to display contact details and if so, which?

**Comment by maxvisser** [comment]
Lets close this for now and make a seperate issue for showing these contact details as it is currently for me still an unknown.
