### ISSUE TITLE
Citizen on-boarding

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#6]
Initial event storming would define commands, events and process as something like:

![screen shot 2018-09-25 at 16 35 09](https://user-images.githubusercontent.com/43416374/46021652-676a6280-c0e1-11e8-95c0-31516d8b247a.png)

The general flow looks like:
<img width="1232" alt="screen shot 2018-10-08 at 08 51 14" src="https://user-images.githubusercontent.com/43416374/46595157-61a85000-cad7-11e8-9868-5d3099e6408f.png">

Details around the Google maps:
<img width="869" alt="screen shot 2018-10-08 at 08 51 21" src="https://user-images.githubusercontent.com/43416374/46595177-72f15c80-cad7-11e8-9c03-afbc5ac844e6.png">

After receiving an invitation through the dashboard (Email, Twitter, Facebook, flyers - #18), the invitee is offered the following options:
<img width="880" alt="screen shot 2018-10-08 at 08 51 26" src="https://user-images.githubusercontent.com/43416374/46595196-84d2ff80-cad7-11e8-8f4e-5174b6d8890d.png">

**Comment by maxvisser** [comment]
I think looking again on how to onboard users from the campaign would benefit the platform most I will move this back to the backlog, lets edit the issue abit. 

@jamalv as you already researched onboarding options abit in your redesign; maybe you could help shape this issue?
