### ISSUE TITLE
Sign up for Mailchimp (or similar)

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#7]
In order to send bulk emails, track campaigns and user click behavior, we should consider using Mailchimp or similar.

Discuss with @errrrk and/or @dimitriirtimid

**Comment by maxvisser** [comment]
@jamalv If @pantyukhov can research mails, he should definitely try looking into mailchimp

**Comment by dimitriirtimid** [comment]
@maxvisser This is an ancient issue (#7). (I thought it could be closed / trashed) What do you want to do here?

**Comment by maxvisser** [comment]
I see this as an next step on implementing something more durable; as we currently use mailto: as an 'email service' If you have similar research suggestion on which other service to use; I think Simple Email Service in AWS is also an option for example. But it not as feature rich as mailchimp;

**Comment by dimitriirtimid** [comment]
Ok, I agree on that. But then please create another more descriptive backlog item for this as this item was meant for campaigning, which is no longer in our scope. Furthermore let's first study the options (mailchimp vs AWS vs ...), then decide and only then start the implementation.
And lastly this item does not contribute to our sprint goal (ready for alphatest), so if Pasha cant do front-end I am fine with him doing research, but this one is definitely a low prio imo.

**Comment by maxvisser** [comment]
I like the idea of making a spec before implementation. This issue is lower on the sprint backlog as the welcome pages and other frontend issues. I agree with you that making a new issue is better. 

I see this issue as a way of already starting on preparing for what is coming as I think researching a mail service will lead to some discussion.
