### ISSUE TITLE
Write on-boarding email template

### ISSUE THREAD

**Issue by errrrk** [local-motion/product#8]
At the moment; the scenario seems to be:
- Campaigners will send email with a link
- No sharing of data
- Citizens may have to re-select their area and/or playground
- Additionally, we'll have a discussion with the campaigners to see if a tighter integration is possible

**Definition of Done:**
- [ ] We need the email contents ready for the campaigners to start sending. 
- [ ] Store in https://github.com/local-motion/product/blob/master/functionality/onboarding/email_template.txt

**Comment by maxvisser** [comment]
I dont see the dependency on the RVG campaign for good onboarding email templates.
