### ISSUE TITLE
Clarify role of ABN AMRO

### ISSUE THREAD

**Issue by dimitriirtimid** [local-motion/product#99]
The role of ABN AMRO in this initiative should be clear

Included the statement "Rookvrije speeltuinen is een initiatief van het Longfonds en ABN AMRO" (NL) or "Smoke-free playgrounds is an initiative of het Longfonds and ABN AMRO" (EN)

DoD
- [x] Decide on the most suitable place to put this statement (footer, about us, etc..) 
- [x] provide a more elaborate description in the FAQ

**Comment by maxvisser** [comment]
@dimitriirtimid lookat #283 maybe move this issue out of the sprint or add it so a different page (not FAQ)

**Comment by dimitriirtimid** [comment]
Rewritten after formal withdrawal of ABN AMRO
